const resources = [
  {
    category: ["Clothing", "Food and Grocery Assistance"],
    name: "Beaverton Seventh-Day Adventist",
    address: "14645 SW Davis Rd. Beaverton, OR 97007",
    phone: "503-646-9828",
    website: "https://beavertonsda.com",
    hours: "Tues. 9 a.m.-noon",
    services: "Walk-in clothes closet and Helping Hands Food Pantry offers food boxes.",
    notes: "Bus: 62, 88",
    transportation: "Bus: 62, 88"
  },
  {
    category: "Clothing",
    name: "Birthright of Hillsboro",
    address: "232 NE Lincoln St., Ste. F, Hillsboro, OR 97124",
    phone: "503-648-6766",
    website: "https://birthright.org/hillsboro",
    hours: "Tues., Wed., Fri. noon-2 p.m.; Thurs. 5:30 p.m.-7:30 p.m.",
    services: "Maternity and baby clothes up to 12 months. Free confidential pregnancy testing, doctor referrals and housing resources.",
    notes: "Proof of pregnancy documentation needed to sign up for OHP and WIC.",
    transportation: "Bus: 46, 48, 57, MAX Blue"
  },
  {
    category: "Clothing",
    name: "Clothes for Kids",
    address: "16550 SW Merlo Rd. Beaverton, OR 97006",
    phone: "503-356-4322",
    website: "https://www.beaverton.k12.or.us/departments/clothes-for-kids",
    hours: "Appointment required",
    services: "Free clothing",
    notes: "For low-income students attending Beaverton schools. Not for adults, infants, or toddlers. Must make an appointment over the phone or through a ParentSquare account.",
    transportation: "Bus: 67, MAX: Blue"
  },
  {
    category: "Clothing",
    name: "Elevate Him",
    address: "1513 SW Marlow St. Ste. A Portland, OR 97225",
    phone: "503-810-1607",
    website: "https://elevatehim.com",
    hours: "Call to make an appointment",
    services: "Men's resource center offering clothes, supportive men's groups, and haircuts and styling",
    notes: "",
    transportation: ""
  },
  {
    category: ["Clothing", "Food and Grocery Assistance"],
    name: "Helping Hands Clothes Closet & Food Pantry",
    address: "14986 NW Cornell Rd. Portland, OR 97229",
    phone: "503-292-9293",
    website: "https://sunsetpres.org/helping-hands",
    hours: "Wed. 9:30-11:30 a.m. and 4-6 p.m.",
    services: "Adult and children's clothing and shoes. Drive-thru style food pantry.",
    notes: "At Sunset Presbyterian Church. No appointment needed.",
    transportation: "Bus: 48"
  },
  {
    category: ["Day Services/Hygiene", "Clothing", "Health Care", "Mental Health & Addiction"],
    name: "Just Compassion of East Washington County",
    address: "12264 SW Hall Blvd. Tigard, OR 97223",
    phone: "503-624-4666",
    website: "https://www.justcompassionewc.com",
    hours: "7 a.m.-7 p.m. daily",
    services: "Welcoming, low-barrier space for people experiencing homelessness. Meals, showers, laundry, clothing closet, medical triage, and mental health support. Connection with providers, help finding stable housing.",
    notes: "For people experiencing homelessness. Showers: First Sunday of month, 1-3pm at Unity Laundry.",
    transportation: "Bus: 12, 78"
  },
  {
    category: ["Day Services/Hygiene", "Housing and Rental Assistance"],
    name: "Open Door HousingWorks",
    address: "34420 SW Tualatin Valley Hwy. Hillsboro, OR 97123",
    phone: "503-640-6689",
    website: "https://opendoorhousingworks.org",
    hours: "Mon.-Fri. 9 a.m.-3 p.m.",
    services: "Day shelter offering meals, food boxes, showers, laundry, mail and phone access. Support in obtaining and retaining housing.",
    notes: "Operates Cornelius Pod Village.",
    transportation: "Bus: 57"
  },
  {
    category: ["Day Services/Hygiene", "Emergency Shelter"],
    name: "Project Homeless Connect",
    address: "SE 6th Ave. Hillsboro, OR 97123 (Across from Tuality Hospital)",
    phone: "971-713-3930",
    website: "https://www.phcwc.org",
    hours: "Daily 7 a.m.-4 p.m.",
    services: "Breakfast and lunch, comfortable day center space, cell phone charging stations, computer access, laundry, showers, food, assistance with obtaining state ID, housing resources, and emergency shelter.",
    notes: "Access Center: 1440 SE 21st Ave, Hillsboro. Shelter at Salvation Army Hope Center.",
    transportation: "Bus: 57, MAX: Blue"
  },
  {
    category: ["Disability and Aging Support", "Veteran Services", "Food and Grocery Assistance"],
    name: "Disability, Aging and Veteran Services (DAVS)",
    address: "5240 NE Elam Young Pkwy., Ste. 300, Hillsboro, OR. 97124",
    phone: "503-846-3060",
    website: "https://www.washingtoncountyor.gov/davs",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Programs and services to enhance quality of life and ensure basic needs are met. Includes Oregon Project Independence, food and nutrition services, and veteran benefits assistance.",
    notes: "For Washington County seniors, veterans, and people with disabilities.",
    transportation: ""
  },
  {
    category: "Disability and Aging Support",
    name: "Social Security Administration",
    address: "11975 SW Second St. Ste. 100 Beaverton, OR 97005",
    phone: "1-800-772-1213",
    website: "https://www.ssa.gov",
    hours: "Mon.-Fri. 9 a.m.-4 p.m.",
    services: "General information about Social Security Disability Insurance and Supplemental Security Income",
    notes: "",
    transportation: "Bus: 53, 57, 78, 88"
  },
  {
    category: ["Domestic Violence/Sexual Assault", "Family and Parenting Support"],
    name: "Domestic Violence Resource Center, Inc. (DVRC)",
    address: "Confidential",
    phone: "503-469-8620 (24/7 crisis line)",
    website: "https://www.dvrc-or.org",
    hours: "Advocacy: Mon.-Thurs. 8:30a.m.-4 p.m.; Counseling: Mon.-Thurs. 10 a.m.-7 p.m.",
    services: "Advocacy for survivors of domestic violence, protective orders, safety planning, individual and group counseling for adults, children, and teens (ages 5-18).",
    notes: "All services are confidential and free of charge. Servicios disponibles en español.",
    transportation: ""
  },
  {
    category: ["Domestic Violence/Sexual Assault", "Health Care"],
    name: "Family Justice Center",
    address: "735 SW 158th Ave. Ste. 100 Beaverton, OR 97006",
    phone: "503-430-8300",
    website: "https://www.fjcwc.org",
    hours: "Mon.-Fri. 8:30a.m.- 4 p.m.",
    services: "Wrap-around services for survivors of Domestic Violence, Sexual Assault, Elder Abuse. Childcare, food, hygiene, legal support, and health referrals.",
    notes: "",
    transportation: ""
  },
  {
    category: "Domestic Violence/Sexual Assault",
    name: "Kim's Place",
    address: "Confidential location",
    phone: "971-415-0007",
    website: "",
    hours: "Call or fill out online application",
    services: "Place of refuge, sober living home specifically for women who have left the sex industry, including trafficked women.",
    notes: "",
    transportation: ""
  },
  {
    category: "Domestic Violence/Sexual Assault",
    name: "Monika's House",
    address: "Confidential location (Hillsboro)",
    phone: "1-866-469-8600 (24/7 crisis line)",
    website: "https://www.dvrc-or.org/monikas-house",
    hours: "Call the crisis line to get connected",
    services: "Safe, confidential emergency shelter and domestic violence crisis hotline. Program of DVRC.",
    notes: "",
    transportation: ""
  },
  {
    category: ["Domestic Violence/Sexual Assault", "Legal Services"],
    name: "Oregon Crime Victims Law Center",
    address: "Confidential",
    phone: "503-208-8160",
    website: "https://www.ocvlc.org",
    hours: "Office visits by appointment only",
    services: "Free legal information, referrals and representation for victims of crime regarding their rights in criminal cases and protective orders.",
    notes: "Call for intake to determine eligibility. Serves all Oregon counties.",
    transportation: ""
  },
  {
    category: ["Domestic Violence/Sexual Assault", "Mental Health & Addiction"],
    name: "Sexual Assault Resource Center (SARC)",
    address: "Confidential",
    phone: "1-888-640-5311 (24/7 crisis line)",
    website: "https://www.sarcor.org",
    hours: "Call the crisis line to get connected",
    services: "Immediate 24-hour response and support to survivors of sexual assault, case management, education, support groups, and free mental health services.",
    notes: "",
    transportation: ""
  },
  {
    category: "Family and Parenting Support",
    name: "Morrison Child and Family Services",
    address: "15455 NW Greenbrier Pkwy. Ste. 200 Beaverton, OR 97006",
    phone: "503-258-4495",
    website: "https://www.morrisonkids.org",
    hours: "Mon.-Fri. 8 a.m-7 p.m.",
    services: "Specialized outpatient mental health services for children birth through 18. Must be under 18 to start services.",
    notes: "Intake hours: 8 a.m.-4 p.m. Mon.-Fri.",
    transportation: ""
  },
  {
    category: "Family and Parenting Support",
    name: "Oregon Child Development Coalition (OCDC)",
    address: "Confidential",
    phone: "503-213-1191 or 503-359-0649",
    website: "https://www.ocdc.net",
    hours: "Call for more information",
    services: "Early Childhood education for children from 6 weeks to 5 years old. School readiness, family advocacy, and healthy meals.",
    notes: "",
    transportation: ""
  },
  {
    category: "Family and Parenting Support",
    name: "Safe Families for Children",
    address: "Confidential",
    phone: "503-906-1027 (Spanish: 503-614-1299)",
    website: "https://safe-families.org",
    hours: "Call or fill out a referral on the website",
    services: "Support to families in crisis by assisting parents with volunteer host families for children and teens while parents work on wellness goals.",
    notes: "All at no cost to families. Serves the tri-county area.",
    transportation: ""
  },
  {
    category: "Family and Parenting Support",
    name: "Safe Oregon",
    address: "Confidential",
    phone: "844-472-3367 (Call or Text 24/7)",
    website: "https://www.safeoregon.com",
    hours: "24/7, 365 days a year",
    services: "Way to report safety threats or potential acts of violence confidentially or anonymously.",
    notes: "Not for immediate emergency response. Email: tips@safeoregon.com",
    transportation: ""
  },
  {
    category: ["Family and Parenting Support", "Clothing"],
    name: "Tigard-Tualatin Family Resource Center",
    address: "9500 SW Murdock St. Tigard, OR 97224 (at James Templeton Elementary)",
    phone: "503-603-1585",
    website: "https://www.ttsdschools.org/Page/247",
    hours: "Open on school days",
    services: "Basic needs resource connection, clothing for babies and children, school supplies, and early learning supports.",
    notes: "Serves families with children ages 0-18 in Tigard-Tualatin School District.",
    transportation: ""
  },
  {
    category: ["Food and Grocery Assistance", "Clothing"],
    name: "Beaverton Resource Center",
    address: "13565 SW Walker Rd. Beaverton, OR 97005",
    phone: "503-591-9025",
    website: "https://beavertonresourcecenter.org",
    hours: "Mon.-Fri. 9 a.m.-2 p.m.; Office: Tues., Wed., Fri. 9 a.m.-1 p.m.",
    services: "Central hub for hunger, housing insecurity, and poverty. Kid's Closet for children's clothing.",
    notes: "Referral-based access to Holy Trinity Food Closet.",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "Cascade Vineyard Church Food Pantry",
    address: "14460 SW 114th Ave. Tigard",
    phone: "503-684-8225",
    website: "https://www.cascadevineyard.org",
    hours: "Thurs. noon-3 p.m.",
    services: "Food pantry lottery system. Available to anyone in need.",
    notes: "House behind Christ the King Lutheran Church.",
    transportation: "Bus: 94"
  },
  {
    category: ["Food and Grocery Assistance", "Clothing"],
    name: "Community Table Food Pantry",
    address: "1095 S Beech St. Cornelius, OR 97113",
    phone: "503-724-9766",
    website: "",
    hours: "1-3 p.m. 1st Wed., 10 a.m.-noon 3rd Sat.",
    services: "Emergency food boxes and clothes closet. Walk-ins welcome.",
    notes: "English/Spanish.",
    transportation: "Bus: 57"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Forest Grove Foursquare Church Food Pantry",
    address: "1719 Cedar St. Forest Grove, OR 97116",
    phone: "503-357-4400",
    website: "https://www.fgfoursquare.org",
    hours: "Thurs. 10 a.m.-12:30 p.m.",
    services: "Food pantry for low-income residents of local areas.",
    notes: "",
    transportation: "Bus: 57"
  },
  {
    category: ["Food and Grocery Assistance", "Clothing"],
    name: "Hillsboro Seventh-Day Adventist",
    address: "367 NE Grant St. Hillsboro, OR 97124",
    phone: "503-648-3922",
    website: "https://hillsborosda.org",
    hours: "Thurs. 6:30-8 p.m.",
    services: "Food boxes and clothing closet for all sizes. For Washington County residents.",
    notes: "",
    transportation: "Bus: 46"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Holy Trinity Food Closet",
    address: "13715 SW Walker Rd. Beaverton, OR 97005",
    phone: "503-591-9025",
    website: "https://h-t.org/food-closet",
    hours: "Tues., Wed., Fri. 10 a.m.-12:30 p.m.",
    services: "Food pantry by appointment through Care to Share.",
    notes: "",
    transportation: "Bus: 59, 62, 67"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Oregon Food Bank",
    address: "Multiple locations",
    phone: "503-439-6510",
    website: "https://www.oregonfoodbank.org",
    hours: "Phone: Mon.-Fri. 8 a.m.-4:30 p.m.",
    services: "Referral service to help find perishable and non-perishable food assistance.",
    notes: "Available in 19 languages.",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "Sherwood Helping Hands",
    address: "22280 SW Washington St. Sherwood, OR 97140",
    phone: "503-625-7975",
    website: "https://www.sherwoodumc.org",
    hours: "9-10 a.m. 3rd Thurs.",
    services: "Food boxes for families by appointment at Sherwood United Methodist Church.",
    notes: "",
    transportation: "Bus: 94"
  },
  {
    category: ["Food and Grocery Assistance", "Meals"],
    name: "St. Francis Food Pantry & Community Meal",
    address: "15659 SW Oregon St. Sherwood, OR 97140",
    phone: "503-625-7067",
    website: "https://stfrancissherwood.org",
    hours: "Pantry: Wed. 9-11 a.m. and 5-7 p.m.; Thurs. 9-11 a.m.; Meal: Sun. 5 p.m.",
    services: "Shopping-style food pantry and community meal on Sundays.",
    notes: "For low-income residents of local areas.",
    transportation: "Bus: 94"
  },
  {
    category: "Food and Grocery Assistance",
    name: "St. Vincent de Paul Food Pantries",
    address: "Multiple locations (Forest Grove, Hillsboro, Tigard, Beaverton, Aloha, Portland)",
    phone: "503-235-8431",
    website: "https://www.svdppdx.org",
    hours: "Varies by location",
    services: "Food pantries, furniture, rent, and utility assistance by appointment.",
    notes: "Call local parish for appointments.",
    transportation: ""
  },
  {
    category: ["Food and Grocery Assistance", "Government Benefits"],
    name: "SNAP (Supplemental Nutrition Assistance Program)",
    address: "Multiple locations",
    phone: "800-699-9075",
    website: "https://www.oregon.gov/odhs/food",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Helps low-income people buy food with a debit card. Apply online at Oregon ONE.",
    notes: "",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "True Life Fellowship Food Pantry",
    address: "1895 NW 169th Pl. Beaverton, OR 97006",
    phone: "503-810-7426",
    website: "https://www.truelifefellowship.com",
    hours: "2nd and 4th Sat. 10 a.m.-1 p.m.",
    services: "Emergency food boxes for low-income Washington County residents.",
    notes: "",
    transportation: "Bus 89"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Tualatin Schoolhouse Pantry",
    address: "3550 SW Borland Rd. Tualatin, OR 97062",
    phone: "503-783-0721",
    website: "https://www.schoolhousepantry.org",
    hours: "Mon. 4-7 p.m., Wed. and Fri. 10 a.m.-1 p.m.",
    services: "Shopping-style pantry twice a month at Rolling Hills Community Church.",
    notes: "",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "Unity Church of Beaverton Food Pantry",
    address: "12650 SW Fifth St. Beaverton, OR 97005",
    phone: "503-646-3364",
    website: "https://www.unityofbeaverton.org",
    hours: "Tues. and Wed. 10 a.m.-4 p.m.",
    services: "Food boxes for specific zip codes (97005, 97006, 97007, 97008).",
    notes: "",
    transportation: "Bus: 52, 76, 78"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Vernonia Cares Food Bank",
    address: "547 Weed Ave. Vernonia, OR 97064",
    phone: "503-429-1414",
    website: "https://vernoniacares.org",
    hours: "Tues. and Thurs. 10 a.m.-2 p.m.",
    services: "Emergency food boxes providing a 3-day supply of groceries.",
    notes: "",
    transportation: ""
  },
  {
    category: ["Food and Grocery Assistance", "Clothing"],
    name: "Wapato Valley Church Food Pantry & Clothes Closet",
    address: "200 Front St. Gaston, OR 97119",
    phone: "503-985-3351",
    website: "https://www.wapatovalley.org/food-pantry-clothes-closet",
    hours: "Thurs. 5-7 p.m.",
    services: "Food bank and clothing closet for local residents.",
    notes: "",
    transportation: ""
  },
  {
    category: ["Food and Grocery Assistance", "Health Care"],
    name: "Women, Infants and Children (WIC)",
    address: "Multiple locations",
    phone: "503-846-3555",
    website: "https://www.washingtoncountyor.gov/wic",
    hours: "Varies by location",
    services: "Healthy food benefits, growth monitoring, breastfeeding support, and referrals.",
    notes: "For pregnant/post-partum women, infants, and children up to age 5.",
    transportation: ""
  },
  {
    category: "Health Care",
    name: "Borland Free Clinic",
    address: "3550 SW Borland Rd. Tualatin, OR 97062",
    phone: "503-974-8887",
    website: "https://borlandfreeclinic.org",
    hours: "Mon. and Thurs. 3-7 p.m.",
    services: "Primary care for uninsured and under-insured patients. Chronic disease management.",
    notes: "Bilingüe. Walk-ins and appts. welcome.",
    transportation: ""
  },
  {
    category: "Health Care",
    name: "Planned Parenthood - Columbia Willamette",
    address: "12220 SW First St. Ste. 200 Beaverton, OR 97005",
    phone: "888-576-7526",
    website: "https://www.plannedparenthood.org",
    hours: "Mon.-Fri. (Varies)",
    services: "Birth control, exams, pregnancy testing, STI treatment, and gender affirming care.",
    notes: "Financial assistance available.",
    transportation: "Bus: 76, 78, MAX"
  },
  {
    category: ["Health Care", "Crisis & Hotlines"],
    name: "Oregon Health Plan (OHP) / Medicaid",
    address: "Confidential",
    phone: "800-699-9075",
    website: "https://one.oregon.gov",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Medical, dental and mental health care access. Apply online at Oregon ONE.",
    notes: "",
    transportation: ""
  },
  {
    category: "Health Care",
    name: "Virginia Garcia Wellness Centers",
    address: "Multiple locations (Beaverton, Hillsboro, Cornelius)",
    phone: "503-352-6000",
    website: "https://virginiagarcia.org",
    hours: "Varies by location",
    services: "Medical, dental, vision, and pharmacy services. Sliding scale fees available.",
    notes: "",
    transportation: ""
  },
  {
    category: ["Housing and Rental Assistance", "Family and Parenting Support", "Veteran Services"],
    name: "Community Action",
    address: "1001 SW Baseline St. Hillsboro, OR 97123",
    phone: "503-615-0770",
    website: "https://caowash.org",
    hours: "Mon.-Thurs. (Phone intake)",
    services: "Rental assistance, energy assistance, early childhood development, and veteran family support.",
    notes: "Requires 72-hour eviction notice for rental aid.",
    transportation: "Bus: 57"
  },
  {
    category: "Housing and Rental Assistance",
    name: "Transcending Hope Recovery Housing",
    address: "Multiple locations",
    phone: "503-475-0636",
    website: "https://transcending-hope.com",
    hours: "",
    services: "Affordable community recovery housing for men, women and families with on-site staff support.",
    notes: "Low-barrier, safe, and structured.",
    transportation: ""
  },
  {
    category: ["Housing and Rental Assistance", "Community Resources"],
    name: "Washington County Housing Services",
    address: "111 NE Lincoln St., Ste. 200-L, Hillsboro, OR 97124",
    phone: "503-846-4794",
    website: "https://www.washingtoncountyor.gov/housing",
    hours: "Varies",
    services: "Rental assistance (Section 8) and affordable housing opportunities.",
    notes: "Most programs have waiting lists.",
    transportation: "Bus: 47, 48, MAX Blue"
  },
  {
    category: "Legal Services",
    name: "Lawyer Referral Service",
    address: "Confidential",
    phone: "503-684-3763",
    website: "https://www.osbar.org/public/ris",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Referrals to attorneys. 30-minute consultation is $35.",
    notes: "Operated by Oregon State Bar.",
    transportation: ""
  },
  {
    category: "Legal Services",
    name: "Oregon Law Center",
    address: "230 NE Second Ave., Ste. F, Hillsboro, OR 97124",
    phone: "503-640-4115",
    website: "https://oregonlawcenter.org",
    hours: "Call for hours",
    services: "Civil legal services for low-income clients: eviction defense, benefits, and family law.",
    notes: "English/Spanish.",
    transportation: "Bus: 48, MAX Blue"
  },
  {
    category: "Legal Services",
    name: "St. Andrew Legal Clinic",
    address: "232 NE Lincoln St. Ste. H, Hillsboro, OR 97123",
    phone: "503-648-1600",
    website: "https://www.salcgroup.org",
    hours: "Mon.-Fri. 9 a.m.-5 p.m.",
    services: "Family law services for low-income individuals on a sliding scale.",
    notes: "",
    transportation: "Bus: 46, MAX"
  },
  {
    category: "Libraries",
    name: "Washington County Libraries (WCCLS)",
    address: "Multiple locations",
    phone: "Various",
    website: "https://www.wccls.org",
    hours: "Varies",
    services: "Safe spaces, free wifi, public computers, and printers.",
    notes: "No library card needed to visit.",
    transportation: ""
  },
  {
    category: "Meals",
    name: "Community Cafe at St. Anthony Parish Center",
    address: "9905 SW McKenzie St. Tigard, OR 97223",
    phone: "503-639-4179",
    website: "",
    hours: "Sun. 5:30-6:30 p.m.",
    services: "Free hot dinners to go.",
    notes: "",
    transportation: "Bus: 45, 94"
  },
  {
    category: ["Meals", "Food and Grocery Assistance"],
    name: "Faith Café",
    address: "5150 SW Watson Ave. Beaverton, OR 97005",
    phone: "503-646-1191",
    website: "https://faithcafe.org",
    hours: "Sun. 4:15 p.m.; last Thurs. of month 4:15 p.m.",
    services: "Free hot meals. Also serves homeless students during school breaks.",
    notes: "Located at Bethel UCC.",
    transportation: ""
  },
  {
    category: ["Emergency Shelter", "Youth & Family Services"],
    name: "Family Promise of Greater Washington County",
    address: "Confidential locations",
    phone: "971-217-8949",
    website: "https://www.familypromisegwc.org",
    hours: "",
    services: "Family shelter and transitional housing support.",
    notes: "",
    transportation: "",
  },
  {
    category: ["Emergency Shelter", "Youth & Family Services"],
    name: "Safe Place for Youth",
    address: "454 SW Washington St. Hillsboro, OR 97123",
    phone: "503-542-2717",
    website: "https://www.boysandgirlsaid.org/safe-place-shelter",
    hours: "24/7",
    services: "Emergency shelter, basic needs, and case management for youth ages 12-20.",
    notes: "Operated by Boys & Girls Aid.",
    transportation: "",
  },
  {
    category: ["Emergency Shelter", "Youth & Family Services"],
    name: "HomePlate Youth Services",
    address: "12520 SW 3rd St. Beaverton, OR 97005",
    phone: "503-320-8965",
    website: "https://www.homeplateyouth.org",
    hours: "Varies",
    services: "Drop-in services and street outreach for youth age 24 and younger.",
    notes: "",
    transportation: "",
  },
  {
    category: "Emergency Shelter",
    name: "Washington County Severe Weather Shelters",
    address: "Multiple locations",
    phone: "503-640-3263",
    website: "https://www.washingtoncountyor.gov/housing/shelters",
    hours: "During weather events",
    services: "24-hour operation during dangerous weather. Meals provided, pets allowed.",
    notes: "Check county website for current active locations.",
    transportation: "",
  },
  {
    category: ["Crisis & Hotlines", "Emergency Shelter", "Housing and Rental Assistance"],
    name: "Community Connect",
    address: "1001 SW Baseline St. Hillsboro, OR 97123",
    phone: "503-640-3263",
    website: "https://caowash.org/programs/housing-stability/community-connect.html",
    hours: "",
    services: "Central homeless response system. Housing assessments and shelter waitlist.",
    notes: "Email: communityconnect@caowash.org",
    transportation: "",
  },
  {
    category: ["Crisis & Hotlines", "Legal Services", "Community Resources"],
    name: "211 Info",
    address: "Confidential",
    phone: "503-222-5555",
    website: "https://www.211info.org",
    hours: "24/7",
    services: "Comprehensive information and referral service for community resources.",
    notes: "",
    transportation: "",
  },
  {
    category: ["Food and Grocery Assistance", "Clothing"],
    name: "GG's House (Giving Grace)",
    address: "2835 19th Avenue, Space 700, Forest Grove, OR 97116",
    phone: "503-359-3871",
    website: "https://www.ggshousegivinggrace.org",
    hours: "Mon-Fri 10am-1pm",
    services: "Ready-to-eat food bags, hygiene items, clothing, and household needs.",
    notes: "Serves veterans, homeless, and people in recovery.",
    transportation: "",
  },
  {
    category: ["Mental Health & Addiction", "Crisis & Hotlines"],
    name: "Lines for Life",
    address: "Confidential",
    phone: "800-273-8255",
    website: "https://www.linesforlife.org",
    hours: "24/7",
    services: "Crisis support and substance abuse resources.",
    notes: "",
    transportation: "",
  },
  {
    category: "Mental Health & Addiction",
    name: "Mental Health & Addiction Association of Oregon (MHAAO)",
    address: "Confidential",
    phone: "503-200-3964",
    website: "https://www.mhaao.org",
    hours: "",
    services: "Peer support resources and referrals.",
    notes: "",
    transportation: "",
  },
  {
    category: ["Mental Health & Addiction", "Specialized Services", "Health Care"],
    name: "NARA (Native American Rehabilitation Association)",
    address: "12360 SW Main St. Tigard, OR 97223",
    phone: "503-625-2040",
    website: "https://www.naranorthwest.org",
    hours: "Mon-Fri 8am-5pm",
    services: "Culturally-specific healthcare, recovery treatment, and behavioral health.",
    notes: "",
    transportation: "",
  },
  {
    category: "Employment & Training",
    name: "WorkSource Oregon",
    address: "241 SW Edgeway Dr. Beaverton, OR 97006",
    phone: "503-526-2700",
    website: "https://worksourceoregon.org",
    hours: "Mon-Fri 8am-5pm",
    services: "Job coaching, career planning, and training resources.",
    notes: "",
    transportation: "",
  },
  {
    category: ["Employment & Training", "Specialized Services", "Food and Grocery Assistance"],
    name: "Centro Cultural de Washington County",
    address: "1110 N Adair St. Cornelius, OR 97113",
    phone: "503-359-0446",
    website: "https://www.centrocultural.org",
    hours: "Mon-Fri 9am-5pm",
    services: "Workforce training, youth programs, elder services, and food pantry.",
    notes: "Focused on Latino families and migrant/seasonal farmworkers.",
    transportation: "",
  },
  {
    category: "Specialized Services",
    name: "Native American Youth and Family Center (NAYA)",
    address: "5135 NE Columbia Blvd. Portland, OR 97218",
    phone: "503-288-8177",
    website: "https://nayapdx.org",
    hours: "Mon-Fri 9am-5pm",
    services: "Culturally-specific education and community involvement for Native Americans.",
    notes: "",
    transportation: "",
  },
  {
    category: "Transportation",
    name: "TriMet Reduced Fare Programs",
    address: "Confidential",
    phone: "503-238-7433",
    website: "https://trimet.org/lowincome",
    hours: "",
    services: "Reduced fares for low-income residents and seniors.",
    notes: "",
    transportation: "",
  },
  {
    category: ["Furniture & Household", "Community Resources"],
    name: "Community Warehouse",
    address: "8380 SW Nyberg St. Tigard, OR 97223",
    phone: "503-347-2147",
    website: "https://www.communitywarehouse.org",
    hours: "Mon-Fri 10am-4pm",
    services: "Essential furnishings for neighbors in need.",
    notes: "",
    transportation: "",
  },
  {
    category: "Community Resources",
    name: "Street Roots",
    address: "211 NW Davis St. Portland, OR 97209",
    phone: "503-228-5657",
    website: "https://www.streetroots.org",
    hours: "",
    services: "Social justice newspaper providing income opportunities for people experiencing homelessness.",
    notes: "",
    transportation: "",
  },
];
