const resources = [
{
    category: ["Food and Grocery Assistance"],
    name: "Beaverton Resource Center",
    address: "13565 SW Walker Rd. Beaverton, OR 97005",
    phone: "503-591-9025",
    lat: 45.46187665904682,
    lng: -122.80369610830516,
    website: "https://beavertonresourcecenter.org/",
    hours: "Mon.-Fri. 9 a.m.-2 p.m.; Office hours: Tues., Wed., and Fri. 9 a.m.-1 p.m.",
    services: "Central hub for those struggling with hunger, housing insecurity and poverty.",
    notes: "Referral-based access to Holy Trinity Food Closet.",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Beaverton Resource Center - Care To Share Food Pantry Network",
    address: "",
    phone: "503-591-9025",
    hours: "Distribution: Mondays 2-4pm, 2nd Wednesdays 10am-12pm, Saturdays",
    services: "Serves Beaverton and Aloha",
    notes: "",
    transportation: "",
  },
{
    category: ["Clothing"],
    name: "Beaverton Resource Center Kid's Closet",
    address: "",
    phone: "503-207-5670",
    hours: "",
    services: "New and like-new children's clothing Baby items, hygiene items, toys, books Referral only Walk-in: Tuesday, Wednesday, Friday 9am-1pm Phone: 503-207-5670",
    notes: "",
    transportation: "",
  },
{
    category: ["Clothing", "Food and Grocery Assistance"],
    name: "Beaverton Seventh-Day Adventist",
    address: "14645 SW Davis Rd. Beaverton, OR 97007",
    phone: "503-646-9828 ext. 16",
    lat: 45.485369135537454,
    lng: -122.79022142804864,
    website: "https://www.beavertonsda.com/community",
    hours: "Tues. 9 a.m.-noon, 12:30-1:30 p.m.",
    services: "Helping Hands Food Pantry offers food boxes.",
    notes: "Bus: 62, 88",
    transportation: "Bus: 62, 88",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Bethel UCC Food Pantry",
    address: "5150 SW Watson Ave, Beaverton, OR 97005",
    phone: "503-646-1191",
    website: "https://www.bethelbeaverton.org/",
    hours: "",
    services: "3-5 days emergency food Partnership with Oregon Food Bank Open during posted hours Hillsboro Area:",
    notes: "",
    transportation: "",
  },
{
    category: ["Clothing"],
    name: "Birthright of Hillsboro",
    address: "232 NE Lincoln St., Ste. F, Hillsboro, OR 97124",
    phone: "503-648-6766",
    lat: 45.538683793367554,
    lng: -122.97719511982997,
    website: "https://birthrightoregon.org/",
    hours: "Tues., Wed., Fri. noon-2 p.m.; Thurs. 5:30 p.m.-7:30 p.m.",
    services: "Maternity and baby clothes up to 12 months. Free confidential pregnancy testing, doctor referrals and housing resources.",
    notes: "Proof of pregnancy documentation needed to sign up for OHP and WIC.",
    transportation: "Bus: 46, 48, 57, MAX Blue",
  },
{
    category: ["Health Care"],
    name: "Borland Free Clinic",
    address: "3550 SW Borland Rd. Tualatin, OR 97062",
    phone: "503-974-8887",
    lat: 45.39848024022749,
    lng: -122.77302180254298,
    website: "https://borlandclinic.org/",
    hours: "Mon. and Thurs. 3-7 p.m.",
    services: "Primary care for uninsured and under-insured patients. Chronic disease management and medication assistance.",
    notes: "Bilingüe. Walk-ins and appts. welcome.",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Cascade Vineyard Church",
    address: "14460 SW 114th Ave. Tigard (house behind Christ the King Lutheran Church)",
    phone: "503-684-8225",
    lat: 45.429659680148696,
    lng: -122.78050013881503,
    website: "https://www.portlandvineyard.org/",
    hours: "Thurs. noon-3 p.m.",
    services: "Food pantry",
    notes: "Lottery system. Available to anyone in need.",
    transportation: "Bus: 94",
  },
{
    category: ["Employment & Training", "Specialized Services"],
    name: "Centro Cultural de Washington County",
    address: "1110 N Adair St, Cornelius, OR 97113",
    phone: "503-359-0446",
    lat: 45.52278628085631,
    lng: -123.07570810869895,
    website: "https://www.centrocultural.org/",
    hours: "",
    services: "Comprehensive services for Latino families Workforce training, youth programs, elder services, food pantry Casa Amparo transitional housing Cornelius Place (affordable housing for seniors)",
    notes: "Website: centrocultural.org.",
    transportation: "",
  },
{
    category: ["Family and Parenting Support"],
    name: "Children and Youth Counseling, DVRC",
    address: "Confidential",
    phone: "503-521-7997",
    hours: "Mon.-Thurs. 10 a.m.-7 p.m.",
    services: "Individual counseling services for children and youth who have witnessed family violence; individual counseling for teens 14 to 18 who have experienced teen dating violence.",
    notes: "Bilingual (Spanish) services available. Children and youth under 14 must have a non-offending parent or guardian willing to receive some parental education. Call for current appointment availability and to schedule intake.",
    transportation: "",
  },
{
    category: ["Clothing"],
    name: "Clothes for Kids",
    address: "16550 SW Merlo Rd. Beaverton, OR 97006",
    phone: "503-356-4322",
    lat: 45.47953538012045,
    lng: -122.80794859078557,
    website: "https://www.beaverton.k12.or.us/departments/student-services/clothes-for-kids",
    hours: "Appointment required",
    services: "Free clothing",
    notes: "For low-income students attending Beaverton schools. Not for adults, infants, or toddlers. Must make an appointment over the phone or through a ParentSquare account.",
    transportation: "Bus: 67, MAX: Blue",
  },
{
    category: ["Housing and Rental Assistance"],
    name: "Community Action",
    address: "1001 SW Baseline St. Hillsboro, OR 97123",
    phone: "503-615-0770",
    lat: 45.51164091708839,
    lng: -122.9717126502882,
    website: "https://caowash.org/",
    hours: "Live phones Mon.-Thurs. starting 8:30 a.m.",
    services: "Limited emergency rental assistance. 72-hour eviction notice required.",
    notes: "Subject to availability. Must be behind on rent. English/Spanish.",
    transportation: "Bus: 57",
  },
{
    category: ["Veteran Services"],
    name: "Community Action - Supportive Services for Veteran Families",
    address: "",
    phone: "503-640-3263",
    hours: "",
    services: "Phone: 503-640-3263 Housing stability, eviction prevention, benefits assistance",
    notes: "Email: communityconnect@caowash.org",
    transportation: "",
  },
{
    category: ["Meals"],
    name: "Community Cafe at St. Anthony Parish Center",
    address: "9905 SW McKenzie St. Tigard, OR 97223",
    phone: "503-639-4179",
    lat: 45.44377839761057,
    lng: -122.79254150216309,
    website: "https://www.satigard.org/",
    hours: "Sun. 5:30-6:30 p.m.",
    services: "Free hot dinners to go.",
    notes: "Doors open 5:30 p.m.",
    transportation: "Bus: 45, 94",
  },
{
    category: ["Crisis & Hotlines"],
    name: "Community Connect",
    address: "",
    phone: "503-640-3263",
    website: "https://caowash.org/programs/housing-stability/homeless-services.html",
    hours: "",
    services: "Central homeless response system Housing assessments, shelter waitlist, case management Waitlist: 1 week to 6 months",
    notes: "Email: communityconnect@caowash.org",
    transportation: "",
  },
{
    category:["Health Care"],
    name: "Community Health Centers",
    address: "",
    phone: "503-359-5564",
    hours: "",
    services: "Various locations throughout county Sliding scale fees available",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Community Table Food Pantry",
    address: "1095 S Beech St. Cornelius, OR 97113",
    phone: "503-724-9766",
    lat: 45.519313353461136,
    lng: -123.06104667033331,
    website: "https://www.facebook.com/CommunityTableFoodPantry/",
    hours: "1-3 p.m. 1st Wed., 10 a.m.-noon 3rd Sat.",
    services: "Emergency food boxes and clothes closet.",
    notes: "Walk-ins welcome. English/Spanish.",
    transportation: "Bus: 57",
  },
{
    category: ["Furniture & Household"],
    name: "Community Warehouse",
    address: "8380 SW Nyberg St, Tualatin, OR 97062",
    phone: "503-447-8100",
    website: "https://www.communitywarehouse.org/",
    hours: "",
    services: "Essential furnishings for neighbors in need Locations in Portland and Tigard Community partnerships",
    notes: "",
    transportation: "",
  },
{
    category: ["Disability and Aging Support"],
    name: "Disability, Aging and Veteran Services",
    address: "5240 NE Elam Young Pkwy., Ste. 300, Hillsboro, OR. 97124",
    phone: "503-846-3060",
    lat: 45.52228867847481,
    lng: -122.96769093590522,
    website: "https://www.washingtoncountyor.gov/davs",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Programs and services to enhance quality of life and ensure basic needs are met. Includes Oregon Project Independence, food and nutrition services.",
    notes: "For Washington County seniors, veterans, and people with disabilities. Most programs serve those 60 years and older, but veterans and benefits enrollment center serves all ages.",
    transportation: "",
  },
{
    category: ["Domestic Violence/Sexual Assault"],
    name: "Domestic Violence Resource Center, Inc.",
    address: "Confidential",
    phone: "503-469-8620 (24/7 crisis line)",
    website: "https://www.dvrc-or.org/",
    hours: "Advocacy & Protective Orders: Mon.-Thurs. 8:30a.m.-4 p.m., Fri. 8:30a.m.-2 p.m.; Counseling Services: Mon.-Thurs. 10 a.m.-7 p.m.",
    services: "Advocacy services for survivors of domestic violence, advocate support for filing protective orders, safety planning, resource referrals, individual and group counseling for adults, individual counseling for children and teens (ages 5-18).",
    notes: "All services are confidential and free of charge. Servicios disponibles en español.",
    transportation: "",
  },
{
    category: ["Veteran Services"],
    name: "Easterseals Oregon - Homeless Veteran Reintegration Program",
    address: "",
    phone: "503-228-5108",
    website: "https://www.easterseals.com/oregon/",
    hours: "",
    services: "Employment assistance for veterans Housing support",
    notes: "",
    transportation: "",
  },
{
    category: ["Clothing"],
    name: "Elevate Him",
    address: "1513 SW Marlow St. Ste. A Portland, OR 97225",
    phone: "503-810-1607",
    lat: 45.51699562961523,
    lng: -122.65781599222775,
    website: "https://elevatehim.com/",
    hours: "Call to make an appointment",
    services: "Men's resource center offering clothes, supportive men's groups, and haircuts and styling",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance", "Meals"],
    name: "Faith Café",
    address: "5150 SW Watson Ave. Beaverton, OR 97005",
    phone: "503-646-1191",
    lat: 45.469001999552326,
    lng: -122.8106338393118,
    website: "https://www.faithcafebeaverton.org/",
    hours: "Sun. 4 p.m.; last Thurs. of month 4 p.m.",
    services: "Free meals: Sundays at 4:15pm, Last Thursday of month at 4:15pm. Also serves homeless students during school breaks",
    notes: "Hosted at Bethel UCC. Free meals Sundays and last Thursday of month at 4:15pm.",
    transportation: "",
  },
{
    category: ["Domestic Violence/Sexual Assault"],
    name: "Family Justice Center",
    address: "735 SW 158th Ave. Ste. 100 Beaverton, OR 97006",
    phone: "503-430-8300",
    lat: 45.46523682374532,
    lng: -122.81905379549116,
    website: "https://www.fjcwc.org/",
    hours: "Mon.-Fri. 8:30a.m.- 4 p.m.",
    services: "Wrap-around services for survivors of Domestic Violence, Sexual Assault, Sexual Exploitation, Elder Abuse, Family Violence, and their children. Childcare, food, hygiene, and legal support, referrals for housing, benefits, and mental health support.",
    notes: "",
    transportation: "",
  },
{
    category: ["Youth & Family Services", "Emergency Shelter"],
    name: "Family Promise of Greater Washington County",
    address: "5625 SW Erickson Ave, Beaverton, OR 97007",
    phone: "971-217-8949",
    lat: 45.49607051673239,
    lng: -122.78672443976784,
    website: "https://www.familypromisegwc.org/",
    hours: "",
    services: "Largest family shelter in Washington County Beaverton, Aloha, Hillsboro, Cornelius, Forest Grove, Banks",
    notes: "Website: familypromisegwc.org. Email: familysupport@fpgwc.org",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Forest Grove Foursquare Church and Food Pantry",
    address: "1719 Cedar St. Forest Grove, OR 97116",
    phone: "503-357-4400",
    lat: 45.51076696220497,
    lng: -123.09072871831425,
    website: "https://www.fgfoursquare.com/",
    hours: "Thurs. 10 a.m.-12:30 p.m.",
    services: "Food pantry",
    notes: "For low-income residents of Dilley, Cornelius, Forest Grove, Gales Creek, Gaston and Laurelwood.",
    transportation: "Bus: 57",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "GG's House",
    address: "Forest Grove, OR",
    phone: "503-359-3871",
    lat: 45.508853998857056,
    lng: -123.09254826491134,
    website: "https://www.ggshousegivinggrace.org/",
    hours: "Monday-Friday, 10am-1pm",
    services: "Forest Grove Ready-to-eat food bags Also provides: Basic hygiene, household needs, new undergarments Veterans, homeless, people recovering Sherwood:",
    notes: "",
    transportation: "",
  },
{
    category: ["Clothing"],
    name: "Helping Hands Clothes Closet",
    address: "14986 NW Cornell Rd. Portland, OR 97229",
    phone: "503-292-9293",
    lat: 45.528555519128794,
    lng: -122.66555509392137,
    website: "https://sunsetpres.org/helping-hands",
    hours: "Wed. 9:30-11:30 a.m. and 4-6 p.m.",
    services: "Adult and children's clothing and shoes",
    notes: "At Sunset Presbyterian Church. No appointment needed.",
    transportation: "Bus: 48",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Helping Hands Food Pantry",
    address: "14986 NW Cornell Rd. Portland, OR 97229",
    phone: "503-292-9293",
    lat: 45.513101731629156,
    lng: -122.65879112869199,
    website: "https://sunsetpres.org/helping-hands",
    hours: "Wed. 9:30-11:30 a.m. and 4-6 p.m.",
    services: "Drive-thru style food pantry",
    notes: "Located at Sunset Presbyterian Church. Volunteers collect a list of groceries and bring it out to you.",
    transportation: "Bus: 48",
  },
{
    category: ["Day Services/Hygiene"],
    name: "Hillsboro Access Center",
    address: "SE 6th Avenue, Hillsboro, OR 97123",
    phone: "971-713-3930",
    hours: "",
    services: "SE 6th Avenue location (planned) Will offer: Daytime shelter, support services, basic necessities Operated by Project Homeless Connect",
    notes: "",
    transportation: "",
  },
{
    category: ["Clothing", "Food and Grocery Assistance"],
    name: "Hillsboro Seventh-Day Adventist",
    address: "367 NE Grant St. Hillsboro, OR 97124",
    phone: "503-648-3922",
    lat: 45.50677835356324,
    lng: -122.9944224547925,
    website: "https://www.hillsborosda.org/",
    hours: "Thurs. 6:30-8 p.m.",
    services: "Clothes closet for all sizes No cost",
    notes: "For Washington County residents.",
    transportation: "Bus: 46",
  },
{
    category: ["Emergency Shelter"],
    name: "Hillsboro Shelter",
    address: "",
    phone: "971-713-3930",
    lat: 45.52790250630169,
    lng: -122.98638245843905,
    website: "https://phcwc.org/",
    hours: "",
    services: "Operated by Project Homeless Connect Year-round adult shelter Part of 400+ bed county-wide system",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Holy Trinity Food Closet",
    address: "13715 SW Walker Rd. Beaverton, OR 97005",
    phone: "503-591-9025",
    lat: 45.47711751599722,
    lng: -122.80835060000545,
    website: "https://h-t.org/food-closet",
    hours: "Tues., Wed., Fri. 10 a.m.-12:30 p.m.",
    services: "Food pantry by appointment.",
    notes: "Make an appointment through Care to Share. May receive assistance twice a month.",
    transportation: "Bus: 59, 62, 67",
  },
{
    category: ["Emergency Shelter", "Youth & Family Services"],
    name: "HomePlate Youth Services",
    address: "12685 SW 4th St, Beaverton, OR 97005",
    phone: "503-567-6591 (Youth Line)",
    lat: 45.49502732750125,
    lng: -122.79984545261466,
    website: "https://www.homeplateyouth.org/",
    hours: "",
    services: "Drop-in services and street outreach For young people age 24 and younger experiencing homelessness",
    notes: "",
    transportation: "",
  },
{
    category: ["Community Resources"],
    name: "Housing Authority of Washington County",
    address: "",
    phone: "503-846-4794",
    website: "https://www.washingtoncountyor.gov/housing/housing-authority-washington-county",
    hours: "",
    services: "Rental assistance voucher programs Regional Long-term Rent Assistance (RLRA) vouchers Section 8 Housing Choice Vouchers",
    notes: "",
    transportation: "",
  },
{
    category: ["Health Care", "Clothing", "Day Services/Hygiene", "Mental Health & Addiction"],
    name: "Just Compassion of East Washington County",
    address: "12264 SW Hall Blvd, Tigard, OR 97223",
    phone: "503-624-4666",
    lat: 45.419804261477076,
    lng: -122.78608015955209,
    website: "https://justcompassion.org/",
    hours: "7 a.m.-7 p.m. daily",
    services: "Welcoming, low-barrier space for people experiencing homelessness. Meals, showers, connection with providers, help finding stable housing.",
    notes: "For people experiencing homelessness.",
    transportation: "Bus: 12, 78",
  },
{
    category: ["Domestic Violence/Sexual Assault"],
    name: "Kim's Place",
    address: "Confidential location",
    phone: "971-415-0007",
    hours: "Call or fill out online application",
    services: "Place of refuge, sober living home.",
    notes: "Caters specifically to women who have left the sex industry, including trafficked women. Goal is to give women dignity, power over their lives, and help them transition into their own home, job, and safety.",
    transportation: "",
  },
{
    category: ["Legal Services"],
    name: "Lawyer Referral Service",
    address: "Confidential",
    phone: "503-684-3763 or 800-452-7636",
    website: "https://www.osbar.org/public/ris/",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Referrals to attorneys in area of needed assistance.",
    notes: "30-minute consultation is $35.",
    transportation: "",
  },
{
    category: ["Mental Health & Addiction"],
    name: "Lines for Life",
    address: "",
    phone: "800-273-8255",
    website: "https://www.linesforlife.org/",
    hours: "",
    services: "Crisis support services Substance abuse resources",
    notes: "",
    transportation: "",
  },
{
    category:["Mental Health & Addiction"],
    name: "Mental Health & Addiction Association of Oregon",
    address: "",
    phone: "503-203-2038",
    hours: "",
    services: "Resources and referrals",
    notes: "",
    transportation: "",
  },
{
    category: ["Domestic Violence/Sexual Assault"],
    name: "Monika's House",
    address: "Confidential location (Hillsboro)",
    phone: "1-866-469-8600 (24/7 crisis line)",
    lat: 45.536031459313044,
    lng: -122.99299559223542,
    website: "https://www.dvrc-or.org/monikas-house",
    hours: "Call the crisis line to get connected",
    services: "Safe, confidential emergency shelter and domestic violence crisis hotline. Services for shelter residents include advocacy, case management, and support groups.",
    notes: "",
    transportation: "",
  },
{
    category: ["Family and Parenting Support"],
    name: "Morrison Child and Family Services",
    address: "15455 NW Greenbrier Pkwy. Ste. 200 Beaverton, OR 97006",
    phone: "503-258-4495",
    lat: 45.48617776211961,
    lng: -122.81779743156102,
    website: "https://morrisonkids.org/",
    hours: "Mon.-Fri. 8 a.m-7 p.m.",
    services: "Specialized outpatient mental health services for children birth through 18. Must be under 18 to start services.",
    notes: "Intake hours: 8 a.m.-4 p.m. Mon.-Fri.",
    transportation: "",
  },
{
    category: ["Specialized Services"],
    name: "Native American Youth and Family Center",
    address: "5135 NE Columbia Blvd, Portland, OR 97218",
    phone: "503-288-8177",
    website: "https://nayapdx.org/",
    hours: "",
    services: "Portland metro area Education, community involvement, culturally-specific programming",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "North Plains Food Bank",
    address: "North Plains Senior Center, 31450 NW Commercial St, North Plains, OR 97133",
    phone: "503-359-3871",
    lat: 45.598990921400095,
    lng: -122.9801691097277,
    website: "https://npfoodbank.com/",
    hours: "",
    services: "2nd Thursday of month, 5-6:30pm North Plains Senior Center PO Box 147, North Plains, OR 97133",
    notes: "Website: npfoodbank.com.",
    transportation: "",
  },
{
    category: ["Day Services/Hygiene", "Housing and Rental Assistance"],
    name: "Open Door HousingWorks",
    address: "34420 SW Tualatin Valley Hwy. Hillsboro, OR 97123",
    phone: "503-640-6689",
    lat: 45.520122788544356,
    lng: -122.99550045242711,
    website: "https://www.odhw.org/",
    hours: "Mon.-Fri. 9 a.m.-3 p.m.",
    services: "Support in obtaining and retaining housing. Shelter referrals and housing services.",
    notes: "",
    transportation: "Bus: 57",
  },
{
    category: ["Family and Parenting Support"],
    name: "Oregon Child Development Coalition",
    address: "Confidential",
    phone: "503-213-1191 or 503-359-0649",
    website: "https://www.ocdc.net/",
    hours: "Call for more information",
    services: "Early Childhood education for children from 6 weeks to 5 years old. Provides school readiness, family advocacy and engagement, health screenings and referrals, healthy meals, and other services.",
    notes: "",
    transportation: "",
  },
{
    category: ["Domestic Violence/Sexual Assault"],
    name: "Oregon Coalition Against Domestic & Sexual Violence",
    address: "",
    phone: "503-230-1951",
    website: "https://www.ocadsv.org/",
    hours: "",
    services: "Search tool for shelter, advocacy, legal services Includes tribe-specific entities",
    notes: "",
    transportation: "",
  },
{
    category: ["Domestic Violence/Sexual Assault", "Legal Services"],
    name: "Oregon Crime Victims Law Center",
    address: "Confidential",
    phone: "503-208-8160",
    website: "https://www.ocvlc.org/",
    hours: "Office visits by appointment only",
    services: "Free legal information, referrals and representation for victims of crime regarding their rights in criminal cases; legal information and representation in protective order cases for survivors of domestic violence, sexual assault and stalking.",
    notes: "Call for intake to determine eligibility for services. Serves all Oregon counties.",
    transportation: "",
  },
{
    category: ["Government Benefits"],
    name: "Oregon Department of Human Services Offices",
    address: "5300 NE Elam Young Pkwy, Hillsboro, OR 97124",
    phone: "503-646-9952",
    lat: 45.52870972052262,
    lng: -122.96485550318013,
    hours: "",
    services: "Beaverton Office: 15625 SW Greystone Ct., Beaverton, OR 97006 Phone: 503-646-9952 Hillsboro Office: Phone: 503-693-4555 Tigard Office: Phone: 503-670-9711 Services Available: SNAP (Food Stamps) TANF (Temporary Assistance for Needy Families) Oregon Health Plan (Medicaid) Child care assistance (ERDC) Cash assistance",
    notes: "",
    transportation: "",
  },
{
    category: ["Specialized Services"],
    name: "Oregon Department of Veterans' Affairs LGBTQIA+ Services",
    address: "",
    phone: "",
    hours: "",
    services: "Specific services and resources available Contact Washington County Veteran Services for info",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Oregon Food Bank",
    address: "Multiple locations",
    phone: "503-439-6510",
    website: "https://www.oregonfoodbank.org/",
    hours: "Phone hours: Mon.-Fri. 8 a.m.-4:30 p.m.",
    services: "Referral service to help individuals find perishable and non-perishable food assistance.",
    notes: "Visit website to find nearest food pantry. Available in 19 languages.",
    transportation: "",
  },
{
    category: ["Health Care"],
    name: "Oregon Health Plan/Medicaid",
    address: "Confidential",
    phone: "800-273-0557",
    website: "https://www.oregon.gov/oha/hsd/ohp/pages/index.aspx",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Assists members with medical, dental or mental health care access. Provides information and referral for OHP.",
    notes: "",
    transportation: "",
  },
{
    category: ["Legal Services"],
    name: "Oregon Law Center",
    address: "230 NE Second Ave., Ste. F, Hillsboro, OR 97124",
    phone: "503-640-4115 (Public Benefits: 1-800-520-5292)",
    lat: 45.51878609958877,
    lng: -122.98744953455734,
    website: "https://oregonlawcenter.org/",
    hours: "Call for walk-in hours",
    services: "Free legal help for low-income residents Cases: Healthcare access, housing, benefits, family law, employment Washington, Columbia, Clatsop, Tillamook, Yamhill counties",
    notes: "English/Spanish. Please call main line for eviction defense.",
    transportation: "Bus: 48, MAX Blue",
  },
{
    category: ["Legal Services"],
    name: "Oregon Law Center Farmworker Program",
    address: "138 NE 3rd Suite 203, Gresham, OR 97030",
    phone: "503-726-4381",
    website: "https://oregonlawcenter.org/",
    hours: "Mon.-Fri. 9 a.m.-5 p.m.",
    services: "Free legal assistance to low-income farmworkers (wage claims, discrimination, harassment, housing).",
    notes: "No appointments necessary. English/Spanish/Mixteco.",
    transportation: "",
  },
{
    category: ["Legal Services"],
    name: "Oregon Public Benefits Hotline",
    address: "",
    phone: "800-520-5292",
    lat: 45.51499394784239,
    lng: -122.65921503336293,
    website: "https://oregonlawcenter.org/how-we-help/public-benefits-hotline/",
    hours: "",
    services: "Monday-Thursday Assistance with state and federal benefits",
    notes: "",
    transportation: "",
  },
{
    category: ["Veteran Services"],
    name: "Oregon Veterans' Emergency Financial Assistance Program",
    address: "",
    phone: "800-692-9666",
    website: "https://www.oregon.gov/odva/Benefits/Pages/Emergency-Assistance.aspx",
    hours: "",
    services: "One-time emergency assistance For veterans and immediate family Housing, utilities, medical/dental, transportation expenses",
    notes: "",
    transportation: "",
  },
{
    category: ["Health Care"],
    name: "Planned Parenthood - Columbia Willamette",
    address: "12220 SW First St. Ste. 200 Beaverton, OR 97005",
    phone: "888-576-7526",
    lat: 45.482733908596614,
    lng: -122.80813905311912,
    website: "https://www.plannedparenthood.org/planned-parenthood-columbia-willamette",
    hours: "Mon. and Wed. 10 a.m.-5:30 p.m.; Tues., Thurs., Fri. 8 a.m.-3:30 p.m.",
    services: "Low-cost birth control, Pap exams, pregnancy testing, STI/HIV treatment, medication abortion, and gender affirming hormone services.",
    notes: "Insured or uninsured accepted. Financial assistance available.",
    transportation: "Bus: 76, 78, MAX",
  },
{
    category: ["Day Services/Hygiene", "Emergency Shelter"],
    name: "Project Homeless Connect",
    address: "SE 6th Ave. Hillsboro, OR 97123 (Located on SE 6th between SE Oak St. and SE Baseline - across from Tuality Hospital.)",
    phone: "971-713-3930",
    lat: 45.536375152614546,
    lng: -122.98844178955815,
    website: "https://phcwc.org/",
    hours: "Wednesday-Sunday, 9am-5pm",
    services: "Breakfast and lunch, comfortable day center space, cell phone charging stations, computer access, laundry, showers, food, assistance with obtaining state ID, housing resources, and other services.",
    notes: "Website: phcwc.org.",
    transportation: "Bus: 57, MAX: Blue",
  },
{
    category: ["Family and Parenting Support"],
    name: "Safe Families for Children",
    address: "Confidential",
    phone: "503-906-1027 (Spanish: 503-614-1299)",
    website: "https://safe-families.org/",
    hours: "Call or fill out a referral on the website",
    services: "Support to families in crisis by assisting parents to get back on their feet without fear of losing custody of their children. Placing children and teens in loving, safe environments with volunteer host families while parents work on wellness goals. Mentoring and coaching of parents.",
    notes: "All at no cost to families. Serves the tri-county area.",
    transportation: "",
  },
{
    category: ["Family and Parenting Support"],
    name: "Safe Oregon",
    address: "Confidential",
    phone: "844-472-3367 (Call or Text 24/7)",
    website: "https://www.safeoregon.com/",
    hours: "24/7, 365 days a year",
    services: "Way to report safety threats or potential acts of violence confidentially or anonymously. Tips are promptly analyzed and forwarded to designated personnel.",
    notes: "Not for immediate emergency response. Email: tips@safeoregon.com, website: www.safeoregon.com/report-a-tip/.",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Salvation Army Meal Services",
    address: "1440 SE 21st Ave, Hillsboro, OR 97123",
    phone: "503-640-4311",
    lat: 45.53860792378832,
    lng: -122.96306371602864,
    website: "https://hillsboro.salvationarmy.org/",
    hours: "",
    services: "Food pantry and meal services Tigard/Tualatin Area:",
    notes: "",
    transportation: "",
  },
{
    category: ["Domestic Violence/Sexual Assault"],
    name: "Sexual Assault Resource Center",
    address: "Confidential",
    phone: "1-888-640-5311 (24/7 crisis line)",
    website: "https://www.sarcor.org/",
    hours: "Call the crisis line to get connected",
    services: "Immediate 24-hour response and support to survivors of sexual assault, case management, education and outreach programs, support groups, and free mental health services.",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Sherwood Food Pantry",
    address: "15659 SW Oregon St, Sherwood, OR 97140",
    phone: "503-625-7067",
    lat: 45.35417444489623,
    lng: -122.85151687026881,
    hours: "Wednesday 9-11am & 5-7pm, Thursday 9-11am",
    services: "Community meal: Sunday at 5pm",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Sherwood Helping Hands",
    address: "22280 SW Washington St. Sherwood, OR 97140",
    phone: "503-625-7975",
    lat: 45.358201374465345,
    lng: -122.84851200634871,
    website: "https://www.sherwoodumc.com/food-pantry.html",
    hours: "9-10 a.m. 3rd Thurs.",
    services: "Food boxes for families by appointment.",
    notes: "Located at Sherwood United Methodist Church.",
    transportation: "Bus: 94",
  },
{
    category: ["Disability and Aging Support"],
    name: "Social Security Administration",
    address: "11975 SW Second St. Ste. 100 Beaverton, OR 97005",
    phone: "1-800-772-1213",
    lat: 45.488704638875674,
    lng: -122.81681655748098,
    website: "https://www.ssa.gov/",
    hours: "Mon.-Fri. 9 a.m.-4 p.m.",
    services: "General information about Social Security Disability Insurance and Supplemental Security Income",
    notes: "",
    transportation: "Bus: 53, 57, 78, 88",
  },
{
    category: ["Legal Services"],
    name: "St. Andrew Legal Clinic-Washington County",
    address: "232 NE Lincoln St. Ste. H, Hillsboro, OR 97123",
    phone: "503-648-1600",
    lat: 45.5096589229676,
    lng: -122.98524855039538,
    website: "https://www.salcgroup.org/",
    hours: "Mon.-Fri. 9 a.m.-5 p.m. (Closed noon-1 p.m.)",
    services: "Family law legal services for low-income individuals.",
    notes: "Charges based on sliding scale. $40 for phone/online consultations.",
    transportation: "Bus: 46, MAX",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "St. Francis Food Pantry",
    address: "15659 SW Oregon St. Sherwood, OR 97140",
    phone: "503-625-7067",
    lat: 45.35035259294123,
    lng: -122.83135850618046,
    website: "https://www.stfrancissherwood.org/social-action-ministries",
    hours: "Wed. 9-11 a.m. and 5-7 p.m.; Thurs. 9-11 a.m.",
    services: "Shopping-style food pantry",
    notes: "For low-income residents of Tualatin, Sherwood, Newberg and King City.",
    transportation: "Bus: 94",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "St. Vincent de Paul Food Pantry - Forest Grove",
    address: "St. Anthony, 1660 Elm St. Forest Grove, OR 97116",
    phone: "503-357-9647",
    lat: 45.52781925278994,
    lng: -123.09684115581837,
    hours: "Call Mon.-Sat. 9 a.m.-noon for appt.",
    services: "Food pantry by appointment.",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "St. Vincent de Paul Food Pantry - Hillsboro",
    address: "St. Matthew's, 442 SE Third Ave. Hillsboro, OR 97123",
    phone: "503-693-7528",
    lat: 45.50081950365671,
    lng: -122.97597456185144,
    website: "https://www.svdphillsboro.com/",
    hours: "Mon. and Wed. 9-11:30 a.m.",
    services: "Food pantry; furniture, rent and utility assistance available.",
    notes: "Mobile kitchen lunch served Wednesdays.",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "St. Vincent de Paul Food Pantry - St. Anthony Tigard",
    address: "9905 SW McKenzie St. Tigard, OR 97223",
    phone: "503-684-8280",
    lat: 45.410986447166536,
    lng: -122.77504131359025,
    website: "https://www.satigard.org/st-vincent-de-paul",
    hours: "Wed. noon-2:30 p.m., Thurs. 1-3 p.m., Sat. 10 a.m.-noon",
    services: "Food pantry.",
    notes: "Serves 97223 and 97224. Provide proof of Tigard residency.",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "St. Vincent de Paul Food Pantry - St. Cecilia",
    address: "12250 SW Fifth St. Beaverton, OR 97005",
    phone: "503-644-2619",
    lat: 45.49285903676389,
    lng: -122.78956705919659,
    website: "https://stceciliachurch.org/st-vincent-de-paul-society",
    hours: "Mon.-Fri. by appt.",
    services: "Food pantry.",
    notes: "Contact Care to Share for appt.",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "St. Vincent de Paul Food Pantry - St. Elizabeth Ann Seton",
    address: "3145 SW 192nd Ave. Aloha, OR 97003",
    phone: "503-649-5841",
    lat: 45.4882477860707,
    lng: -122.86729476202869,
    website: "https://www.seasaloha.org/",
    hours: "Mon.-Fri. 11 a.m.-2 p.m. by appt.",
    services: "Food pantry.",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "St. Vincent de Paul Food Pantry - St. Juan Diego",
    address: "5995 NW 178th Ave. Portland, OR 97229",
    phone: "503-985-6046",
    lat: 45.51987416655848,
    lng: -122.66401444995408,
    website: "https://www.stjuandiego.org/outreach",
    hours: "Mon. 4-5:30 p.m., Fri. 11 a.m.-12:30 p.m.",
    services: "Food pantry.",
    notes: "",
    transportation: "",
  },
{
    category: ["Community Resources"],
    name: "Street Roots",
    address: "",
    phone: "503-228-5657",
    website: "https://www.streetroots.org/",
    hours: "",
    services: "Weekly social justice newspaper Sold by people experiencing homelessness to earn income",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Supplemental Nutrition Assistance Program",
    address: "Multiple locations",
    phone: "503-693-4555 (Hillsboro), 503-646-9952 (Beaverton), 503-670-9711 (Tigard)",
    website: "https://www.oregon.gov/odhs/food/pages/snap.aspx",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Helps low-income people buy food. Benefits provided on a debit card.",
    notes: "Apply online at www.oregon.gov/DHS.",
    transportation: "MAX Blue (Hillsboro), Bus 48, 67 (Beaverton), Bus 76, 78 (Tigard)",
  },
{
    category: ["Family and Parenting Support"],
    name: "Tigard-Tualatin Family Resource Center",
    address: "9500 SW Murdock St. Tigard, OR 97224 (James Templeton Elementary School)",
    phone: "503-603-1585",
    lat: 45.44276696764978,
    lng: -122.77366534546798,
    website: "https://www.ttsdschools.org/Page/8953",
    hours: "Open on school days",
    services: "Basic needs resource connection, information on how to get clothing for babies and children, school supplies, and early learning supports.",
    notes: "Serves families with children ages 0-18 who live within the Tigard-Tualatin School District boundary.",
    transportation: "",
  },
{
    category: ["Housing and Rental Assistance"],
    name: "Transcending Hope Tri-County Supportive Housing",
    address: "Multiple locations",
    phone: "503-475-0636",
    website: "https://transcending-hope.com/",
    hours: "",
    services: "Affordable community housing program for men, women and families with on-site staff support.",
    notes: "",
    transportation: "",
  },
{
    category: ["Transportation"],
    name: "TriMet Reduced Fare Programs",
    address: "",
    phone: "503-238-7433",
    website: "https://trimet.org/lowincome/",
    hours: "",
    services: "Partner organizations help obtain reduced fares Just Compassion is partner organization",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "True Life Fellowship Food Pantry",
    address: "1895 NW 169th Pl. Beaverton, OR 97006",
    phone: "503-810-7426",
    lat: 45.47647545315365,
    lng: -122.78823430629748,
    website: "https://www.truelifefellowship.org/",
    hours: "2nd and 4th Sat. of the month 10 a.m.-1 p.m.",
    services: "Emergency food boxes",
    notes: "For low-income Washington County residents.",
    transportation: "Bus 89",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Tualatin Schoolhouse Pantry",
    address: "3550 SW Borland Rd, Tualatin, OR 97062",
    phone: "503-783-0721",
    lat: 45.383696810027104,
    lng: -122.76740494797639,
    website: "https://www.tualatinfoodpantry.org/",
    hours: "Mon. 4-7 p.m., Wed. and Fri. 10 a.m.-1 p.m.",
    services: "Rolling Hills Community Church (lower level) 5,600 sq ft grocery store-style pantry One of largest in Washington/Clackamas counties Executive Director: Danielle Schneider Forest Grove Area:",
    notes: "For residents of Durham, Lake Oswego, Tualatin, West Linn and Wilsonville located at Rolling Hills Community Church.",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Unity Church of Beaverton Food Pantry",
    address: "12650 SW Fifth St. Beaverton, OR 97005",
    phone: "503-646-3364",
    lat: 45.469970344282316,
    lng: -122.80015880056006,
    website: "https://www.unityofbeavertonchurch.org/",
    hours: "Tues. and Wed. 10 a.m.-4 p.m.",
    services: "Food boxes",
    notes: "For low-income residents within specific zip codes: 97005, 97006, 97007, 97008.",
    transportation: "Bus: 52, 76, 78",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Vernonia Cares Food Bank",
    address: "547 Weed Ave. Vernonia, OR 97064",
    phone: "503-429-1414",
    lat: 45.869509059879505,
    lng: -123.19995753669347,
    website: "https://www.facebook.com/VernoniaCares/",
    hours: "Tues. and Thurs. 10 a.m.-2 p.m.",
    services: "Emergency food boxes provide 3-day supply of groceries",
    notes: "For low-income residents of Vernonia, Timber, Manning and Buxton.",
    transportation: "",
  },
{
    category:["Veteran Services"],
    name: "Veterans Affairs Supportive Housing",
    address: "",
    phone: "503-273-5114",
    hours: "",
    services: "272 vouchers available in Washington County Rental assistance + VA case management For homeless veterans and families",
    notes: "",
    transportation: "",
  },
{
    category: ["Health Care"],
    name: "Virginia Garcia - Beaverton Dental @ The Round",
    address: "12600 SW Crescent St. Beaverton, OR 97005",
    phone: "503-718-3675",
    lat: 45.49628618508533,
    lng: -122.81699388465758,
    website: "https://virginiagarcia.org/",
    hours: "Mon. and Fri. 7 a.m.-6 p.m.",
    services: "Dental Services",
    notes: "",
    transportation: "Bus: 20, 57, MAX Blue",
  },
{
    category: ["Health Care"],
    name: "Virginia Garcia - Beaverton Vision",
    address: "12600 SW Crescent St. Ste. 130, Beaverton, OR 97005",
    phone: "503-352-1699",
    lat: 45.47985063009413,
    lng: -122.78913984541234,
    website: "https://virginiagarcia.org/",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Vision care",
    notes: "",
    transportation: "",
  },
{
    category: ["Health Care"],
    name: "Virginia Garcia - Beaverton Wellness Center",
    address: "2725 SW Cedar Hills Blvd. Ste. 200, Beaverton, OR 97005",
    phone: "503-352-6000",
    lat: 45.468698348601194,
    lng: -122.81792910110607,
    website: "https://virginiagarcia.org/",
    hours: "Mon. and Fri. 8 a.m.-7 p.m.",
    services: "Medical services",
    notes: "",
    transportation: "Bus: 20, 57, MAX Blue",
  },
{
    category: ["Health Care"],
    name: "Virginia Garcia - Beaverton Wellness Center Pharmacy",
    address: "2725 SW Cedar Hills Blvd. Ste. 200, Beaverton, OR 97005",
    phone: "503-352-6006",
    lat: 45.49599438108018,
    lng: -122.8188488316756,
    website: "https://virginiagarcia.org/",
    hours: "Mon.-Fri. (various); Wed. 10 a.m.-6 p.m.",
    services: "Pharmacy",
    notes: "",
    transportation: "Bus: 20, 57, MAX Blue",
  },
{
    category: ["Health Care"],
    name: "Virginia Garcia - Cornelius Wellness Center",
    address: "1151 N Adair St. Cornelius, OR 97113",
    phone: "503-359-5564",
    lat: 45.50326235113019,
    lng: -123.0769699240459,
    website: "https://virginiagarcia.org/",
    hours: "Mon., Tues., Fri. 8:30 a.m.-5:15 p.m.; Wed. 9:30 a.m.; Thurs. 10:30 a.m.-7:15 p.m.",
    services: "Medical, Dental (503-359-8505), Vision (503-352-8543), and Pharmacy (503-352-8852).",
    notes: "Dental appts by phone only; no walk-ins.",
    transportation: "Bus: 57",
  },
{
    category: ["Health Care"],
    name: "Virginia Garcia - Hillsboro Clinic",
    address: "226 SE Eighth Ave. Hillsboro, OR 97123",
    phone: "503-601-7400",
    lat: 45.51252685787505,
    lng: -122.96935989180136,
    website: "https://virginiagarcia.org/",
    hours: "Mon.-Fri. 8 a.m.-7 p.m.",
    services: "Primary care clinic and Vision Clinic.",
    notes: "Closed 1st, 3rd, 5th Wed 1-2 p.m. Vision clinic operated by Pacific University College of Optometry.",
    transportation: "MAX Blue",
  },
{
    category: ["Health Care"],
    name: "Virginia Garcia - Hillsboro Dental",
    address: "730 SE Oak St. Ste. A and B, Hillsboro, OR 97123",
    phone: "503-352-2354",
    lat: 45.51398222837002,
    lng: -122.97793346249591,
    website: "https://virginiagarcia.org/",
    hours: "Mon.-Fri. 7 a.m.-6 p.m.",
    services: "Dental",
    notes: "Appointments by phone only. No walk-ins.",
    transportation: "Bus: 46, 47, 57, MAX Blue",
  },
{
    category: ["Health Care"],
    name: "Virginia Garcia - Hillsboro Women's Clinic",
    address: "333 SE 7th Ave. Suite 550, Hillsboro, OR 97123",
    phone: "503-359-5564",
    lat: 45.5113918752925,
    lng: -122.97767751294589,
    website: "https://virginiagarcia.org/",
    hours: "Mon., Wed., Fri. 8 a.m.-5 p.m.; Tues., Thurs. 10 a.m.-7 p.m.",
    services: "Women's health services.",
    notes: "",
    transportation: "",
  },
{
    category: ["Food and Grocery Assistance"],
    name: "Wapato Valley Church Food Pantry",
    address: "200 Front St. Gaston, OR 97119",
    phone: "503-985-3351",
    lat: 45.42657867574059,
    lng: -123.15763538350018,
    website: "https://www.wapatovalley.org/",
    hours: "Thurs. 5-7 p.m.",
    services: "Food bank and clothing closet.",
    notes: "For low-income residents of Gales Creek, Gaston, Laurelwood and Cherry Grove.",
    transportation: "",
  },
{
    category: ["Emergency Shelter"],
    name: "Washington County Family Shelter Network",
    address: "",
    phone: "503-640-3263",
    website: "https://caowash.org/programs/housing-stability/homeless-services.html",
    hours: "",
    services: "Administered by Community Action Shelter for homeless families, case management, eviction prevention",
    notes: "",
    transportation: "",
  },
{
    category: ["Employment & Training"],
    name: "Washington County Housing Careers Pilot Program",
    address: "",
    phone: "",
    hours: "",
    services: "Training and 500-hour paid internship ($17/hr) Open Door HousingWorks partnership Focus on BIPOC and LGBTQIA+ recruitment",
    notes: "",
    transportation: "",
  },
{
    category: ["Housing and Rental Assistance"],
    name: "Washington County Housing Services",
    address: "111 NE Lincoln St., Ste. 200-L, Hillsboro, OR 97124",
    phone: "503-846-4794",
    lat: 45.52699652820724,
    lng: -122.9986487001899,
    website: "https://www.washingtoncountyor.gov/housing",
    hours: "Mon. 8:30-11:30 a.m.; Wed. 1-4 p.m.; Fri. 8:30-11:30 a.m.",
    services: "Rental assistance and affordable housing opportunities (Section 8 and public housing).",
    notes: "Most programs have waiting lists. English/Spanish.",
    transportation: "Bus: 47, 48, MAX Blue",
  },
{
    category: ["Libraries"],
    name: "Washington County Libraries",
    address: "Multiple locations",
    phone: "Various",
    website: "https://www.wccls.org/",
    hours: "Varies by location",
    services: "Safe cooling/warming places, free wifi, public computers, and printers. Visit wccls.org/libraries.",
    notes: "No library card needed to visit.",
    transportation: "Varies by location.",
  },
{
    category: ["Emergency Shelter"],
    name: "Washington County Severe Weather Shelters",
    address: "",
    phone: "211",
    lat: 45.50208180288795,
    lng: -122.97629563988616,
    website: "https://www.washingtoncountyor.gov/housing/severe-weather-shelter-response",
    hours: "",
    services: "Activate during dangerous weather conditions Multiple locations (check county website for current locations) 24-hour operation during weather events Hot meals provided, pets allowed No one turned away",
    notes: "",
    transportation: "",
  },
{
    category: ["Veteran Services"],
    name: "Washington County Veteran Services",
    address: "",
    phone: "503-846-3060",
    website: "https://www.washingtoncountyor.gov/davs/veterans-services",
    hours: "",
    services: "5240 NE Elam Young Parkway, Suite 300, Hillsboro Free assistance with VA benefits and claims Veteran Service Officers (VSOs) available",
    notes: "",
    transportation: "",
  },
{
    category: ["Health Care", "Food and Grocery Assistance"],
    name: "Women, Infants and Children",
    address: "Multiple locations",
    phone: "503-846-3000",
    website: "https://www.washingtoncountyor.gov/wic",
    hours: "Mon. 10 a.m.-6:30 p.m. (Hillsboro/Beaverton); Tues.-Fri. 8 a.m.-4:30 p.m.",
    services: "Healthy food, nutrition education, breastfeeding support For pregnant individuals and families with young children",
    notes: "For pregnant/post-partum women, infants, and children up to age 5.",
    transportation: "MAX Blue (Hillsboro), Bus 52, 76, 78 (Beaverton)",
  },
{
    category: ["Employment & Training"],
    name: "WorkSource Oregon",
    address: "241 SW Edgeway Dr, Hillsboro, OR 97124",
    phone: "503-681-0221",
    website: "https://worksourceoregon.org/",
    hours: "",
    services: "Free one-stop career center All services free",
    notes: "",
    transportation: "",
  },
{
    category: ["Employment & Training"],
    name: "Worksystems",
    address: "1618 SW 1st Ave, Ste 450, Portland, OR 97201",
    phone: "503-478-7300",
    website: "https://www.worksystems.org/",
    hours: "",
    services: "Coordinates services and invests in job training Helps match job seekers with regional industry needs",
    notes: "",
    transportation: "",
  }
];