const resources = [
  // Clothing
  {
    category: "Clothing",
    name: "Beaverton Seventh-Day Adventist",
    address: "14645 SW Davis Rd. Beaverton, OR 97007",
    phone: "503-646-9828",
    hours: "Tues. 9 a.m.-noon",
    services: "Walk-in clothes closet",
    notes: "Bus: 62, 88",
    transportation: "Bus: 62, 88"
  },
  {
    category: "Clothing",
    name: "Birthright of Hillsboro",
    address: "232 NE Lincoln St., Ste. F, Hillsboro, OR 97124",
    phone: "503-648-6766",
    hours: "Tues., Wed., Fri. noon-2 p.m.; Thurs. 5:30 p.m.-7:30 p.m.",
    services: "Maternity and baby clothes up to 12 months. Free confidential pregnancy testing, doctor referrals and housing resources.",
    notes: "Proof of pregnancy documentation needed to sign up for OHP and WIC.",
    transportation: "Bus: 46, 48, 57, MAX Blue"
  },
  {
    category: "Clothing",
    name: "Clothes for Kids",
    address: "16550 SW Merlo Rd. Beaverton, OR 97006",
    phone: "503-356-4322",
    hours: "Appointment required",
    services: "Free clothing",
    notes: "For low-income students attending Beaverton schools. Not for adults, infants, or toddlers. Must make an appointment over the phone or through a ParentSquare account.",
    transportation: "Bus: 67, MAX: Blue"
  },
  {
    category: "Clothing",
    name: "Elevate Him",
    address: "1513 SW Marlow St. Ste. A Portland, OR 97225",
    phone: "503-810-1607",
    hours: "Call to make an appointment",
    services: "Men's resource center offering clothes, supportive men's groups, and haircuts and styling",
    notes: "",
    transportation: ""
  },
  {
    category: "Clothing",
    name: "Helping Hands Clothes Closet",
    address: "14986 NW Cornell Rd. Portland, OR 97229",
    phone: "503-292-9293",
    hours: "Wed. 9:30-11:30 a.m. and 4-6 p.m.",
    services: "Adult and children's clothing and shoes",
    notes: "At Sunset Presbyterian Church. No appointment needed.",
    transportation: "Bus: 48"
  },

  // Day Services/Hygiene
  {
    category: "Day Services/Hygiene",
    name: "Just Compassion of East Washington County",
    address: "12264 SW Hall Blvd. Tigard, OR 97223",
    phone: "503-624-4666",
    hours: "7 a.m.-7 p.m. daily",
    services: "Welcoming, low-barrier space for people experiencing homelessness. Meals, showers, connection with providers, help finding stable housing.",
    notes: "For people experiencing homelessness.",
    transportation: "Bus: 12, 78"
  },
  {
    category: "Day Services/Hygiene",
    name: "Open Door HousingWorks",
    address: "34420 SW Tualatin Valley Hwy. Hillsboro, OR 97123",
    phone: "503-640-6689",
    hours: "Mon.-Fri. 9 a.m.-3 p.m.",
    services: "Day shelter offering meals, food boxes, showers, laundry, mail and phone access",
    notes: "",
    transportation: "Bus: 57"
  },
  {
    category: "Day Services/Hygiene",
    name: "Project Homeless Connect",
    address: "SE 6th Ave. Hillsboro, OR 97123 (Located on SE 6th between SE Oak St. and SE Baseline - across from Tuality Hospital.)",
    phone: "971-713-3930",
    hours: "Daily 7 a.m.-4 p.m.",
    services: "Breakfast and lunch, comfortable day center space, cell phone charging stations, computer access, laundry, showers, food, assistance with obtaining state ID, housing resources, and other services.",
    notes: "",
    transportation: "Bus: 57, MAX: Blue"
  },

  // Disability and Aging Support
  {
    category: "Disability and Aging Support",
    name: "Disability, Aging and Veteran Services",
    address: "5240 NE Elam Young Pkwy., Ste. 300, Hillsboro, OR. 97124",
    phone: "503-846-3060",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Programs and services to enhance quality of life and ensure basic needs are met. Includes Oregon Project Independence, food and nutrition services.",
    notes: "For Washington County seniors, veterans, and people with disabilities. Most programs serve those 60 years and older, but veterans and benefits enrollment center serves all ages.",
    transportation: ""
  },
  {
    category: "Disability and Aging Support",
    name: "Social Security Administration",
    address: "11975 SW Second St. Ste. 100 Beaverton, OR 97005",
    phone: "1-800-772-1213",
    hours: "Mon.-Fri. 9 a.m.-4 p.m.",
    services: "General information about Social Security Disability Insurance and Supplemental Security Income",
    notes: "",
    transportation: "Bus: 53, 57, 78, 88"
  },

  // Domestic Violence/Sexual Assault
  {
    category: "Domestic Violence/Sexual Assault",
    name: "Domestic Violence Resource Center, Inc.",
    address: "Confidential",
    phone: "503-469-8620 (24/7 crisis line)",
    hours: "Advocacy & Protective Orders: Mon.-Thurs. 8:30a.m.-4 p.m., Fri. 8:30a.m.-2 p.m.; Counseling Services: Mon.-Thurs. 10 a.m.-7 p.m.",
    services: "Advocacy services for survivors of domestic violence, advocate support for filing protective orders, safety planning, resource referrals, individual and group counseling for adults, individual counseling for children and teens (ages 5-18).",
    notes: "All services are confidential and free of charge. Servicios disponibles en español.",
    transportation: ""
  },
  {
    category: "Domestic Violence/Sexual Assault",
    name: "Family Justice Center",
    address: "735 SW 158th Ave. Ste. 100 Beaverton, OR 97006",
    phone: "503-430-8300",
    hours: "Mon.-Fri. 8:30a.m.- 4 p.m.",
    services: "Wrap-around services for survivors of Domestic Violence, Sexual Assault, Sexual Exploitation, Elder Abuse, Family Violence, and their children. Childcare, food, hygiene, and legal support, referrals for housing, benefits, and mental health support.",
    notes: "",
    transportation: ""
  },
  {
    category: "Domestic Violence/Sexual Assault",
    name: "Kim's Place",
    address: "Confidential location",
    phone: "971-415-0007",
    hours: "Call or fill out online application",
    services: "Place of refuge, sober living home.",
    notes: "Caters specifically to women who have left the sex industry, including trafficked women. Goal is to give women dignity, power over their lives, and help them transition into their own home, job, and safety.",
    transportation: ""
  },
  {
    category: "Domestic Violence/Sexual Assault",
    name: "Monika's House",
    address: "Confidential location (Hillsboro)",
    phone: "1-866-469-8600 (24/7 crisis line)",
    hours: "Call the crisis line to get connected",
    services: "Safe, confidential emergency shelter and domestic violence crisis hotline. Services for shelter residents include advocacy, case management, and support groups.",
    notes: "",
    transportation: ""
  },
  {
    category: "Domestic Violence/Sexual Assault",
    name: "Oregon Crime Victims Law Center",
    address: "Confidential",
    phone: "503-208-8160",
    hours: "Office visits by appointment only",
    services: "Free legal information, referrals and representation for victims of crime regarding their rights in criminal cases; legal information and representation in protective order cases for survivors of domestic violence, sexual assault and stalking.",
    notes: "Call for intake to determine eligibility for services. Serves all Oregon counties.",
    transportation: ""
  },
  {
    category: "Domestic Violence/Sexual Assault",
    name: "Sexual Assault Resource Center (SARC)",
    address: "Confidential",
    phone: "1-888-640-5311 (24/7 crisis line)",
    hours: "Call the crisis line to get connected",
    services: "Immediate 24-hour response and support to survivors of sexual assault, case management, education and outreach programs, support groups, and free mental health services.",
    notes: "",
    transportation: ""
  },

  // Family and Parenting Support
  {
    category: "Family and Parenting Support",
    name: "Children and Youth Counseling, DVRC",
    address: "Confidential",
    phone: "503-521-7997",
    hours: "Mon.-Thurs. 10 a.m.-7 p.m.",
    services: "Individual counseling services for children and youth who have witnessed family violence; individual counseling for teens 14 to 18 who have experienced teen dating violence.",
    notes: "Bilingual (Spanish) services available. Children and youth under 14 must have a non-offending parent or guardian willing to receive some parental education. Call for current appointment availability and to schedule intake.",
    transportation: ""
  },
  {
    category: "Family and Parenting Support",
    name: "Morrison Child and Family Services",
    address: "15455 NW Greenbrier Pkwy. Ste. 200 Beaverton, OR 97006",
    phone: "503-258-4495",
    hours: "Mon.-Fri. 8 a.m-7 p.m.",
    services: "Specialized outpatient mental health services for children birth through 18. Must be under 18 to start services.",
    notes: "Intake hours: 8 a.m.-4 p.m. Mon.-Fri.",
    transportation: ""
  },
  {
    category: "Family and Parenting Support",
    name: "Oregon Child Development Coalition (OCDC)",
    address: "Confidential",
    phone: "503-213-1191 or 503-359-0649",
    hours: "Call for more information",
    services: "Early Childhood education for children from 6 weeks to 5 years old. Provides school readiness, family advocacy and engagement, health screenings and referrals, healthy meals, and other services.",
    notes: "",
    transportation: ""
  },
  {
    category: "Family and Parenting Support",
    name: "Safe Families for Children",
    address: "Confidential",
    phone: "503-906-1027 (Spanish: 503-614-1299)",
    hours: "Call or fill out a referral on the website",
    services: "Support to families in crisis by assisting parents to get back on their feet without fear of losing custody of their children. Placing children and teens in loving, safe environments with volunteer host families while parents work on wellness goals. Mentoring and coaching of parents.",
    notes: "All at no cost to families. Serves the tri-county area.",
    transportation: ""
  },
  {
    category: "Family and Parenting Support",
    name: "Safe Oregon",
    address: "Confidential",
    phone: "844-472-3367 (Call or Text 24/7)",
    hours: "24/7, 365 days a year",
    services: "Way to report safety threats or potential acts of violence confidentially or anonymously. Tips are promptly analyzed and forwarded to designated personnel.",
    notes: "Not for immediate emergency response. Email: tips@safeoregon.com, website: www.safeoregon.com/report-a-tip/.",
    transportation: ""
  },
  {
    category: "Family and Parenting Support",
    name: "Tigard-Tualatin Family Resource Center",
    address: "9500 SW Murdock St. Tigard, OR 97224 (James Templeton Elementary School)",
    phone: "503-603-1585",
    hours: "Open on school days",
    services: "Basic needs resource connection, information on how to get clothing for babies and children, school supplies, and early learning supports.",
    notes: "Serves families with children ages 0-18 who live within the Tigard-Tualatin School District boundary.",
    transportation: ""
  },

  // Food and Grocery Assistance
  {
    category: "Food and Grocery Assistance",
    name: "Beaverton Resource Center",
    address: "13565 SW Walker Rd. Beaverton, OR 97005",
    phone: "503-591-9025",
    hours: "Mon.-Fri. 9 a.m.-2 p.m.; Office hours: Tues., Wed., and Fri. 9 a.m.-1 p.m.",
    services: "Central hub for those struggling with hunger, housing insecurity and poverty.",
    notes: "Referral-based access to Holy Trinity Food Closet.",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "Beaverton Seventh-Day Adventist",
    address: "14645 SW Davis Rd. Beaverton, OR 97007",
    phone: "503-646-9828 ext. 16",
    hours: "Tues. 9 a.m.-noon, 12:30-1:30 p.m.",
    services: "Helping Hands Food Pantry offers food boxes.",
    notes: "",
    transportation: "Bus: 62, 88"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Cascade Vineyard Church",
    address: "14460 SW 114th Ave. Tigard (house behind Christ the King Lutheran Church)",
    phone: "503-684-8225",
    hours: "Thurs. noon-3 p.m.",
    services: "Food pantry",
    notes: "Lottery system. Available to anyone in need.",
    transportation: "Bus: 94"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Community Table Food Pantry",
    address: "1095 S Beech St. Cornelius, OR 97113",
    phone: "503-724-9766",
    hours: "1-3 p.m. 1st Wed., 10 a.m.-noon 3rd Sat.",
    services: "Emergency food boxes and clothes closet.",
    notes: "Walk-ins welcome. English/Spanish.",
    transportation: "Bus: 57"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Forest Grove Foursquare Church and Food Pantry",
    address: "1719 Cedar St. Forest Grove, OR 97116",
    phone: "503-357-4400",
    hours: "Thurs. 10 a.m.-12:30 p.m.",
    services: "Food pantry",
    notes: "For low-income residents of Dilley, Cornelius, Forest Grove, Gales Creek, Gaston and Laurelwood.",
    transportation: "Bus: 57"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Helping Hands Food Pantry",
    address: "14986 NW Cornell Rd. Portland, OR 97229",
    phone: "503-292-9293",
    hours: "Wed. 9:30-11:30 a.m. and 4-6 p.m.",
    services: "Drive-thru style food pantry",
    notes: "Located at Sunset Presbyterian Church. Volunteers collect a list of groceries and bring it out to you.",
    transportation: "Bus: 48"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Hillsboro Seventh-Day Adventist",
    address: "367 NE Grant St. Hillsboro, OR 97124",
    phone: "503-648-3922",
    hours: "Thurs. 6:30-8 p.m.",
    services: "Food boxes and clothing closet.",
    notes: "For Washington County residents.",
    transportation: "Bus: 46"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Holy Trinity Food Closet",
    address: "13715 SW Walker Rd. Beaverton, OR 97005",
    phone: "503-591-9025",
    hours: "Tues., Wed., Fri. 10 a.m.-12:30 p.m.",
    services: "Food pantry by appointment.",
    notes: "Make an appointment through Care to Share. May receive assistance twice a month.",
    transportation: "Bus: 59, 62, 67"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Oregon Food Bank",
    address: "Multiple locations",
    phone: "503-439-6510",
    hours: "Phone hours: Mon.-Fri. 8 a.m.-4:30 p.m.",
    services: "Referral service to help individuals find perishable and non-perishable food assistance.",
    notes: "Visit website to find nearest food pantry. Available in 19 languages.",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "Sherwood Helping Hands",
    address: "22280 SW Washington St. Sherwood, OR 97140",
    phone: "503-625-7975",
    hours: "9-10 a.m. 3rd Thurs.",
    services: "Food boxes for families by appointment.",
    notes: "Located at Sherwood United Methodist Church.",
    transportation: "Bus: 94"
  },
  {
    category: "Food and Grocery Assistance",
    name: "St. Francis Food Pantry",
    address: "15659 SW Oregon St. Sherwood, OR 97140",
    phone: "503-625-7067",
    hours: "Wed. 9-11 a.m. and 5-7 p.m.; Thurs. 9-11 a.m.",
    services: "Shopping-style food pantry",
    notes: "For low-income residents of Tualatin, Sherwood, Newberg and King City.",
    transportation: "Bus: 94"
  },
  {
    category: "Food and Grocery Assistance",
    name: "St. Vincent de Paul Food Pantry - Forest Grove",
    address: "St. Anthony, 1660 Elm St. Forest Grove, OR 97116",
    phone: "503-357-9647",
    hours: "Call Mon.-Sat. 9 a.m.-noon for appt.",
    services: "Food pantry by appointment.",
    notes: "",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "St. Vincent de Paul Food Pantry - Hillsboro",
    address: "St. Matthew's, 442 SE Third Ave. Hillsboro, OR 97123",
    phone: "503-693-7528",
    hours: "Mon. and Wed. 9-11:30 a.m.",
    services: "Food pantry; furniture, rent and utility assistance available.",
    notes: "Mobile kitchen lunch served Wednesdays.",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "St. Vincent de Paul Food Pantry - St. Anthony Tigard",
    address: "9905 SW McKenzie St. Tigard, OR 97223",
    phone: "503-684-8280",
    hours: "Wed. noon-2:30 p.m., Thurs. 1-3 p.m., Sat. 10 a.m.-noon",
    services: "Food pantry.",
    notes: "Serves 97223 and 97224. Provide proof of Tigard residency.",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "St. Vincent de Paul Food Pantry - St. Cecilia",
    address: "12250 SW Fifth St. Beaverton, OR 97005",
    phone: "503-644-2619",
    hours: "Mon.-Fri. by appt.",
    services: "Food pantry.",
    notes: "Contact Care to Share for appt.",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "St. Vincent de Paul Food Pantry - St. Elizabeth Ann Seton",
    address: "3145 SW 192nd Ave. Aloha, OR 97003",
    phone: "503-649-5841",
    hours: "Mon.-Fri. 11 a.m.-2 p.m. by appt.",
    services: "Food pantry.",
    notes: "",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "St. Vincent de Paul Food Pantry - St. Juan Diego",
    address: "5995 NW 178th Ave. Portland, OR 97229",
    phone: "503-985-6046",
    hours: "Mon. 4-5:30 p.m., Fri. 11 a.m.-12:30 p.m.",
    services: "Food pantry.",
    notes: "",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "Supplemental Nutrition Assistance Program (SNAP)",
    address: "Multiple locations",
    phone: "503-693-4555 (Hillsboro), 503-646-9952 (Beaverton), 503-670-9711 (Tigard)",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Helps low-income people buy food. Benefits provided on a debit card.",
    notes: "Apply online at www.oregon.gov/DHS.",
    transportation: "MAX Blue (Hillsboro), Bus 48, 67 (Beaverton), Bus 76, 78 (Tigard)"
  },
  {
    category: "Food and Grocery Assistance",
    name: "True Life Fellowship Food Pantry",
    address: "1895 NW 169th Pl. Beaverton, OR 97006",
    phone: "503-810-7426",
    hours: "2nd and 4th Sat. of the month 10 a.m.-1 p.m.",
    services: "Emergency food boxes",
    notes: "For low-income Washington County residents.",
    transportation: "Bus 89"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Tualatin Schoolhouse Pantry",
    address: "3550 SW Borland Rd. Tualatin, OR 97062",
    phone: "503-783-0721",
    hours: "Mon. 4-7 p.m., Wed. and Fri. 10 a.m.-1 p.m.",
    services: "Shopping-style pantry twice a month.",
    notes: "For residents of Durham, Lake Oswego, Tualatin, West Linn and Wilsonville located at Rolling Hills Community Church.",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "Unity Church of Beaverton Food Pantry",
    address: "12650 SW Fifth St. Beaverton, OR 97005",
    phone: "503-646-3364",
    hours: "Tues. and Wed. 10 a.m.-4 p.m.",
    services: "Food boxes",
    notes: "For low-income residents within specific zip codes: 97005, 97006, 97007, 97008.",
    transportation: "Bus: 52, 76, 78"
  },
  {
    category: "Food and Grocery Assistance",
    name: "Vernonia Cares Food Bank",
    address: "547 Weed Ave. Vernonia, OR 97064",
    phone: "503-429-1414",
    hours: "Tues. and Thurs. 10 a.m.-2 p.m.",
    services: "Emergency food boxes provide 3-day supply of groceries",
    notes: "For low-income residents of Vernonia, Timber, Manning and Buxton.",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "Wapato Valley Church Food Pantry",
    address: "200 Front St. Gaston, OR 97119",
    phone: "503-985-3351",
    hours: "Thurs. 5-7 p.m.",
    services: "Food bank and clothing closet.",
    notes: "For low-income residents of Gales Creek, Gaston, Laurelwood and Cherry Grove.",
    transportation: ""
  },
  {
    category: "Food and Grocery Assistance",
    name: "Women, Infants and Children (WIC)",
    address: "Multiple locations",
    phone: "503-846-3555",
    hours: "Mon. 10 a.m.-6:30 p.m. (Hillsboro/Beaverton); Tues.-Fri. 8 a.m.-4:30 p.m.",
    services: "Healthy food benefits, growth monitoring, and referrals.",
    notes: "For pregnant/post-partum women, infants, and children up to age 5.",
    transportation: "MAX Blue (Hillsboro), Bus 52, 76, 78 (Beaverton)"
  },

  // Health Care
  {
    category: "Health Care",
    name: "Borland Free Clinic",
    address: "3550 SW Borland Rd. Tualatin, OR 97062",
    phone: "503-974-8887",
    hours: "Mon. and Thurs. 3-7 p.m.",
    services: "Primary care for uninsured and under-insured patients. Chronic disease management and medication assistance.",
    notes: "Bilingüe. Walk-ins and appts. welcome.",
    transportation: ""
  },
  {
    category: "Health Care",
    name: "Planned Parenthood - Columbia Willamette",
    address: "12220 SW First St. Ste. 200 Beaverton, OR 97005",
    phone: "888-576-7526",
    hours: "Mon. and Wed. 10 a.m.-5:30 p.m.; Tues., Thurs., Fri. 8 a.m.-3:30 p.m.",
    services: "Low-cost birth control, Pap exams, pregnancy testing, STI/HIV treatment, medication abortion, and gender affirming hormone services.",
    notes: "Insured or uninsured accepted. Financial assistance available.",
    transportation: "Bus: 76, 78, MAX"
  },
  {
    category: "Health Care",
    name: "Oregon Health Plan/Medicaid",
    address: "Confidential",
    phone: "800-273-0557",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Assists members with medical, dental or mental health care access. Provides information and referral for OHP.",
    notes: "",
    transportation: ""
  },
  {
    category: "Health Care",
    name: "Virginia Garcia - Beaverton Dental @ The Round",
    address: "12600 SW Crescent St. Beaverton, OR 97005",
    phone: "503-718-3675",
    hours: "Mon. and Fri. 7 a.m.-6 p.m.",
    services: "Dental Services",
    notes: "",
    transportation: "Bus: 20, 57, MAX Blue"
  },
  {
    category: "Health Care",
    name: "Virginia Garcia - Beaverton Wellness Center",
    address: "2725 SW Cedar Hills Blvd. Ste. 200, Beaverton, OR 97005",
    phone: "503-352-6000",
    hours: "Mon. and Fri. 8 a.m.-7 p.m.",
    services: "Medical services",
    notes: "",
    transportation: "Bus: 20, 57, MAX Blue"
  },
  {
    category: "Health Care",
    name: "Virginia Garcia - Beaverton Wellness Center Pharmacy",
    address: "2725 SW Cedar Hills Blvd. Ste. 200, Beaverton, OR 97005",
    phone: "503-352-6006",
    hours: "Mon.-Fri. (various); Wed. 10 a.m.-6 p.m.",
    services: "Pharmacy",
    notes: "",
    transportation: "Bus: 20, 57, MAX Blue"
  },
  {
    category: "Health Care",
    name: "Virginia Garcia - Beaverton Vision",
    address: "12600 SW Crescent St. Ste. 130, Beaverton, OR 97005",
    phone: "503-352-1699",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Vision care",
    notes: "",
    transportation: ""
  },
  {
    category: "Health Care",
    name: "Virginia Garcia - Cornelius Wellness Center",
    address: "1151 N Adair St. Cornelius, OR 97113",
    phone: "503-359-5564",
    hours: "Mon., Tues., Fri. 8:30 a.m.-5:15 p.m.; Wed. 9:30 a.m.; Thurs. 10:30 a.m.-7:15 p.m.",
    services: "Medical, Dental (503-359-8505), Vision (503-352-8543), and Pharmacy (503-352-8852).",
    notes: "Dental appts by phone only; no walk-ins.",
    transportation: "Bus: 57"
  },
  {
    category: "Health Care",
    name: "Virginia Garcia - Hillsboro Clinic",
    address: "226 SE Eighth Ave. Hillsboro, OR 97123",
    phone: "503-601-7400",
    hours: "Mon.-Fri. 8 a.m.-7 p.m.",
    services: "Primary care clinic and Vision Clinic.",
    notes: "Closed 1st, 3rd, 5th Wed 1-2 p.m. Vision clinic operated by Pacific University College of Optometry.",
    transportation: "MAX Blue"
  },
  {
    category: "Health Care",
    name: "Virginia Garcia - Hillsboro Dental",
    address: "730 SE Oak St. Ste. A and B, Hillsboro, OR 97123",
    phone: "503-352-2354",
    hours: "Mon.-Fri. 7 a.m.-6 p.m.",
    services: "Dental",
    notes: "Appointments by phone only. No walk-ins.",
    transportation: "Bus: 46, 47, 57, MAX Blue"
  },
  {
    category: "Health Care",
    name: "Virginia Garcia - Hillsboro Women's Clinic",
    address: "333 SE 7th Ave. Suite 550, Hillsboro, OR 97123",
    phone: "503-359-5564",
    hours: "Mon., Wed., Fri. 8 a.m.-5 p.m.; Tues., Thurs. 10 a.m.-7 p.m.",
    services: "Women's health services.",
    notes: "",
    transportation: ""
  },

  // Housing and Rental Assistance
  {
    category: "Housing and Rental Assistance",
    name: "Community Action",
    address: "1001 SW Baseline St. Hillsboro, OR 97123",
    phone: "503-615-0770",
    hours: "Live phones Mon.-Thurs. starting 8:30 a.m.",
    services: "Limited emergency rental assistance. 72-hour eviction notice required.",
    notes: "Subject to availability. Must be behind on rent. English/Spanish.",
    transportation: "Bus: 57"
  },
  {
    category: "Housing and Rental Assistance",
    name: "Open Door HousingWorks",
    address: "34420 SW Tualatin Valley Hwy. Hillsboro, OR 97123",
    phone: "503-640-6689",
    hours: "Mon.-Fri. 9 a.m.-5 p.m.",
    services: "Support in obtaining and retaining housing. Shelter referrals and housing services.",
    notes: "",
    transportation: "Bus: 57"
  },
  {
    category: "Housing and Rental Assistance",
    name: "Transponding Hope Tri-County Supportive Housing",
    address: "Multiple locations",
    phone: "503-475-0636",
    hours: "",
    services: "Affordable community housing program for men, women and families with on-site staff support.",
    notes: "",
    transportation: ""
  },
  {
    category: "Housing and Rental Assistance",
    name: "Washington County Housing Services",
    address: "111 NE Lincoln St., Ste. 200-L, Hillsboro, OR 97124",
    phone: "503-846-4794",
    hours: "Mon. 8:30-11:30 a.m.; Wed. 1-4 p.m.; Fri. 8:30-11:30 a.m.",
    services: "Rental assistance and affordable housing opportunities (Section 8 and public housing).",
    notes: "Most programs have waiting lists. English/Spanish.",
    transportation: "Bus: 47, 48, MAX Blue"
  },

  // Legal Services
  {
    category: "Legal Services",
    name: "Lawyer Referral Service",
    address: "Confidential",
    phone: "503-684-3763 or 800-452-7636",
    hours: "Mon.-Fri. 8 a.m.-5 p.m.",
    services: "Referrals to attorneys in area of needed assistance.",
    notes: "30-minute consultation is $35.",
    transportation: ""
  },
  {
    category: "Legal Services",
    name: "Oregon Crime Victims Law Center",
    address: "Confidential",
    phone: "503-208-8160",
    hours: "Office visits by appointment only",
    services: "Free legal representation regarding crime victims' rights; protective order cases for survivors of DV, sexual assault and stalking.",
    notes: "Serves all Oregon counties.",
    transportation: ""
  },
  {
    category: "Legal Services",
    name: "Oregon Law Center",
    address: "230 NE Second Ave., Ste. F, Hillsboro, OR 97124",
    phone: "503-640-4115 (Public Benefits: 1-800-520-5292)",
    hours: "Call for walk-in hours",
    services: "Civil legal services for low-income clients. No criminal or personal injury cases.",
    notes: "English/Spanish. Please call main line for eviction defense.",
    transportation: "Bus: 48, MAX Blue"
  },
  {
    category: "Legal Services",
    name: "Oregon Law Center Farmworker Program",
    address: "138 NE 3rd Suite 203, Gresham, OR 97030",
    phone: "503-726-4381",
    hours: "Mon.-Fri. 9 a.m.-5 p.m.",
    services: "Free legal assistance to low-income farmworkers (wage claims, discrimination, harassment, housing).",
    notes: "No appointments necessary. English/Spanish/Mixteco.",
    transportation: ""
  },
  {
    category: "Legal Services",
    name: "St. Andrew Legal Clinic-Washington County",
    address: "232 NE Lincoln St. Ste. H, Hillsboro, OR 97123",
    phone: "503-648-1600",
    hours: "Mon.-Fri. 9 a.m.-5 p.m. (Closed noon-1 p.m.)",
    services: "Family law legal services for low-income individuals.",
    notes: "Charges based on sliding scale. $40 for phone/online consultations.",
    transportation: "Bus: 46, MAX"
  },

  // Libraries
  {
    category: "Libraries",
    name: "Washington County Libraries",
    address: "Multiple locations",
    phone: "Various",
    hours: "Varies by location",
    services: "Safe cooling/warming places, free wifi, public computers, and printers. Visit wccls.org/libraries.",
    notes: "No library card needed to visit.",
    transportation: "Varies by location."
  },

  // Meals
  {
    category: "Meals",
    name: "Community Cafe at St. Anthony Parish Center",
    address: "9905 SW McKenzie St. Tigard, OR 97223",
    phone: "503-639-4179",
    hours: "Sun. 5:30-6:30 p.m.",
    services: "Free hot dinners to go.",
    notes: "Doors open 5:30 p.m.",
    transportation: "Bus: 45, 94"
  },
  {
    category: "Meals",
    name: "Faith Café",
    address: "5150 SW Watson Ave. Beaverton, OR 97005",
    phone: "",
    hours: "Sun. 4 p.m.; last Thurs. of month 4 p.m.",
    services: "Free meals: Sundays at 4:15pm, Last Thursday of month at 4:15pm. Also serves homeless students during school breaks",
    notes: "",
    transportation: ""
  },
  {
    category: "Emergency Shelter",
    name: "Project Homeless Connect (PHC)",
    address: "Salvation Army Hope Center, 1440 SE 21st Ave, Hillsboro",
    phone: "971-713-3930",
    hours: "Wednesday-Sunday, 9am-5pm",
    services: "Emergency shelter (congregate and non-congregate), outreach, housing case management",
    notes: "Website: phcwc.org.",
    transportation: "",
  },
  {
    category: "Emergency Shelter",
    name: "Washington County Family Shelter Network",
    address: "",
    phone: "503-640-3263",
    hours: "",
    services: "Administered by Community Action Shelter for homeless families, case management, eviction prevention",
    notes: "",
    transportation: "",
  },
  {
    category: "Emergency Shelter",
    name: "Family Promise of Greater Washington County",
    address: "",
    phone: "971-217-8949",
    hours: "",
    services: "Largest family shelter in Washington County Beaverton, Aloha, Hillsboro, Cornelius, Forest Grove, Banks",
    notes: "Website: familypromisegwc.org. Email: familysupport@fpgwc.org",
    transportation: "",
  },
  {
    category: "Emergency Shelter",
    name: "Hillsboro Shelter",
    address: "",
    phone: "",
    hours: "",
    services: "Operated by Project Homeless Connect Year-round adult shelter Part of 400+ bed county-wide system",
    notes: "",
    transportation: "",
  },
  {
    category: "Emergency Shelter",
    name: "Cornelius Pod Village",
    address: "",
    phone: "",
    hours: "",
    services: "Operated by Open Door HousingWorks Conestoga Hut shelters Opened September 2023",
    notes: "",
    transportation: "",
  },
  {
    category: "Emergency Shelter",
    name: "Safe Place for Youth",
    address: "",
    phone: "503-542-2717",
    hours: "",
    services: "Youth ages 12-20 Emergency shelter, basic needs, case management For youth experiencing homelessness or at risk due to home instability",
    notes: "",
    transportation: "",
  },
  {
    category: "Emergency Shelter",
    name: "HomePlate Youth Services",
    address: "",
    phone: "503-320-8965",
    hours: "",
    services: "Drop-in services and street outreach For young people age 24 and younger experiencing homelessness",
    notes: "",
    transportation: "",
  },
  {
    category: "Emergency Shelter",
    name: "Washington County Severe Weather Shelters",
    address: "",
    phone: "",
    hours: "",
    services: "Activate during dangerous weather conditions Multiple locations (check county website for current locations) 24-hour operation during weather events Hot meals provided, pets allowed No one turned away",
    notes: "",
    transportation: "",
  },
  {
    category: "Emergency Shelter",
    name: "Safe Parking Program",
    address: "",
    phone: "",
    hours: "",
    services: "Safe, legal parking for vehicles Sanitation services and case management consultations",
    notes: "",
    transportation: "",
  },
  {
    category: "Day Services/Hygiene",
    name: "Project Homeless Connect Access Center",
    address: "1440 SE 21st Ave, Hillsboro",
    phone: "",
    hours: "Wednesday-Sunday, 9am-5pm",
    services: "Showers, laundry, meals, resource connections",
    notes: "",
    transportation: "",
  },
  {
    category: "Day Services/Hygiene",
    name: "Just Compassion Drop-in Services",
    address: "12264 SW Hall Blvd, Tigard",
    phone: "",
    hours: "",
    services: "Outreach and daytime services",
    notes: "",
    transportation: "",
  },
  {
    category: "Day Services/Hygiene",
    name: "Hillsboro Access Center",
    address: "",
    phone: "",
    hours: "",
    services: "SE 6th Avenue location (planned) Will offer: Daytime shelter, support services, basic necessities Operated by Project Homeless Connect",
    notes: "",
    transportation: "",
  },
  {
    category: "Crisis & Hotlines",
    name: "Community Connect",
    address: "",
    phone: "503-640-3263",
    hours: "",
    services: "Central homeless response system Housing assessments, shelter waitlist, case management Waitlist: 1 week to 6 months",
    notes: "Email: communityconnect@caowash.org",
    transportation: "",
  },
  {
    category: "Crisis & Hotlines",
    name: "211 Info",
    address: "",
    phone: "503-222-5555",
    hours: "",
    services: "Information and referral service Connects people with community resources Serves Oregon and Southwest Washington",
    notes: "Website: 211info.org.",
    transportation: "",
  },
  {
    category: "Food and Grocery Assistance",
    name: "Beaverton Resource Center - Care To Share Food Pantry Network",
    address: "",
    phone: "503-591-9025",
    hours: "Distribution: Mondays 2-4pm, 2nd Wednesdays 10am-12pm, Saturdays",
    services: "Serves Beaverton and Aloha",
    notes: "",
    transportation: "",
  },
  {
    category: "Food and Grocery Assistance",
    name: "Bethel UCC Food Pantry",
    address: "",
    phone: "",
    hours: "",
    services: "3-5 days emergency food Partnership with Oregon Food Bank Open during posted hours Hillsboro Area:",
    notes: "",
    transportation: "",
  },
  {
    category: "Food and Grocery Assistance",
    name: "Hillsboro SDA Church Community Services",
    address: "",
    phone: "503-648-3922",
    hours: "Thursday 6:30-8pm",
    services: "Emergency food boxes, clothes closet Oregon Food Bank partner",
    notes: "",
    transportation: "",
  },
  {
    category: "Food and Grocery Assistance",
    name: "Salvation Army Hope Center",
    address: "1440 SE 21st Ave, Hillsboro",
    phone: "",
    hours: "",
    services: "Food pantry and meal services Tigard/Tualatin Area:",
    notes: "",
    transportation: "",
  },
  {
    category: "Food and Grocery Assistance",
    name: "Tualatin Food Pantry",
    address: "",
    phone: "",
    hours: "",
    services: "Rolling Hills Community Church (lower level) 5,600 sq ft grocery store-style pantry One of largest in Washington/Clackamas counties Executive Director: Danielle Schneider Forest Grove Area:",
    notes: "",
    transportation: "",
  },
  {
    category: "Food and Grocery Assistance",
    name: "North Plains Food Bank",
    address: "",
    phone: "503-359-3871",
    hours: "",
    services: "2nd Thursday of month, 5-6:30pm North Plains Senior Center PO Box 147, North Plains, OR 97133",
    notes: "Website: npfoodbank.com.",
    transportation: "",
  },
  {
    category: "Food and Grocery Assistance",
    name: "GG's House",
    address: "",
    phone: "503-359-3871",
    hours: "Monday-Friday, 10am-1pm",
    services: "Forest Grove Ready-to-eat food bags Also provides: Basic hygiene, household needs, new undergarments Veterans, homeless, people recovering Sherwood:",
    notes: "",
    transportation: "",
  },
  {
    category: "Food and Grocery Assistance",
    name: "Sherwood Food Pantry",
    address: "",
    phone: "",
    hours: "Wednesday 9-11am & 5-7pm, Thursday 9-11am",
    services: "Community meal: Sunday at 5pm",
    notes: "",
    transportation: "",
  },
  {
    category: "Food and Grocery Assistance",
    name: "Faith Café (Bethel UCC)",
    address: "",
    phone: "",
    hours: "",
    services: "Free meals: Sundays at 4:15pm, Last Thursday of month at 4:15pm Also serves homeless students during school breaks",
    notes: "",
    transportation: "",
  },
  {
    category: "Food and Grocery Assistance",
    name: "Salvation Army Meal Services",
    address: "",
    phone: "",
    hours: "",
    services: "Multiple locations Hot meals for people in need",
    notes: "",
    transportation: "",
  },
  {
    category: "Food and Grocery Assistance",
    name: "DAVS Nutrition and Meal Programs",
    address: "",
    phone: "",
    hours: "",
    services: "Meal sites for adults 60+ Home delivery options available Contact: Washington County DAVS",
    notes: "",
    transportation: "",
  },
  {
    category: "Clothing",
    name: "Just Compassion",
    address: "",
    phone: "",
    hours: "",
    services: "Hygiene services Showers: First Sunday of month, 1-3pm",
    notes: "",
    transportation: "",
  },
  {
    category: "Clothing",
    name: "Beaverton Resource Center Kid's Closet",
    address: "",
    phone: "503-207-5670",
    hours: "",
    services: "New and like-new children's clothing Baby items, hygiene items, toys, books Referral only Walk-in: Tuesday, Wednesday, Friday 9am-1pm Phone: 503-207-5670",
    notes: "",
    transportation: "",
  },
  {
    category: "Clothing",
    name: "Hillsboro SDA Church",
    address: "",
    phone: "",
    hours: "",
    services: "Clothes closet for all sizes No cost",
    notes: "",
    transportation: "",
  },
  {
    category: "Health Care",
    name: "Just Compassion Medical Services",
    address: "12264 SW Hall Blvd, Tigard",
    phone: "",
    hours: "",
    services: "Medical triage at Shelter & Resource Center",
    notes: "",
    transportation: "",
  },
  {
    category: "Health Care",
    name: "Washington County WIC",
    address: "",
    phone: "503-846-3000",
    hours: "",
    services: "Healthy food, nutrition education, breastfeeding support For pregnant individuals and families with young children",
    notes: "",
    transportation: "",
  },
  {
    category: "Health Care",
    name: "Oregon Health Plan (Medicaid)",
    address: "",
    phone: "",
    hours: "",
    services: "Apply through Oregon Department of Human Services Multiple DHS offices in Washington County",
    notes: "",
    transportation: "",
  },
  {
    category: "Health Care",
    name: "Community Health Centers",
    address: "",
    phone: "",
    hours: "",
    services: "Various locations throughout county Sliding scale fees available",
    notes: "",
    transportation: "",
  },
  {
    category: "Mental Health & Addiction",
    name: "Just Compassion Mental Health Services",
    address: "",
    phone: "",
    hours: "",
    services: "Counseling and mental health support Part of Shelter & Resource Center",
    notes: "",
    transportation: "",
  },
  {
    category: "Mental Health & Addiction",
    name: "Mental Health & Addiction Association of Oregon",
    address: "",
    phone: "",
    hours: "",
    services: "Resources and referrals",
    notes: "",
    transportation: "",
  },
  {
    category: "Mental Health & Addiction",
    name: "Lines for Life",
    address: "",
    phone: "",
    hours: "",
    services: "Crisis support services Substance abuse resources",
    notes: "",
    transportation: "",
  },
  {
    category: "Mental Health & Addiction",
    name: "NARA (Northwest Portland Area Indian Health Board)",
    address: "",
    phone: "",
    hours: "",
    services: "Culturally-specific services Substance use recovery treatment Behavioral and primary healthcare",
    notes: "",
    transportation: "",
  },
  {
    category: "Legal Services",
    name: "Oregon Law Center (OLC)",
    address: "230 NE 2nd Ave, Suite F, Hillsboro",
    phone: "503-640-4115",
    hours: "",
    services: "Free legal help for low-income residents Cases: Healthcare access, housing, benefits, family law, employment Washington, Columbia, Clatsop, Tillamook, Yamhill counties",
    notes: "",
    transportation: "",
  },
  {
    category: "Legal Services",
    name: "Oregon Public Benefits Hotline",
    address: "",
    phone: "800-520-5292",
    hours: "",
    services: "Monday-Thursday Assistance with state and federal benefits",
    notes: "",
    transportation: "",
  },
  {
    category: "Legal Services",
    name: "Commons Law Center",
    address: "810 NW Marshall St, #300, Portland",
    phone: "",
    hours: "",
    services: "Nonprofit law firm Family law, estate planning Sliding scale fees",
    notes: "",
    transportation: "",
  },
  {
    category: "Employment & Training",
    name: "IRCO Workforce Programs",
    address: "",
    phone: "",
    hours: "",
    services: "Career planning, training, scholarships Career coaching, work experiences, job placement Focused support for: Immigrants, refugees, houseless, low-income job seekers",
    notes: "",
    transportation: "",
  },
  {
    category: "Employment & Training",
    name: "WorkSource Oregon",
    address: "",
    phone: "",
    hours: "",
    services: "Free one-stop career center All services free",
    notes: "",
    transportation: "",
  },
  {
    category: "Employment & Training",
    name: "Washington County Housing Careers Pilot Program",
    address: "",
    phone: "",
    hours: "",
    services: "Training and 500-hour paid internship ($17/hr) Open Door HousingWorks partnership Focus on BIPOC and LGBTQIA+ recruitment",
    notes: "",
    transportation: "",
  },
  {
    category: "Employment & Training",
    name: "Worksystems",
    address: "",
    phone: "",
    hours: "",
    services: "Coordinates services and invests in job training Helps match job seekers with regional industry needs",
    notes: "",
    transportation: "",
  },
  {
    category: "Employment & Training",
    name: "Centro Cultural de Washington County",
    address: "",
    phone: "",
    hours: "",
    services: "Workforce training Services for Latino families and migrant/seasonal farmworkers",
    notes: "Website: centrocultural.org.",
    transportation: "",
  },
  {
    category: "Veteran Services",
    name: "Washington County Veteran Services",
    address: "",
    phone: "503-846-3060",
    hours: "",
    services: "5240 NE Elam Young Parkway, Suite 300, Hillsboro Free assistance with VA benefits and claims Veteran Service Officers (VSOs) available",
    notes: "",
    transportation: "",
  },
  {
    category: "Veteran Services",
    name: "Veterans Affairs Supportive Housing (VASH)",
    address: "",
    phone: "",
    hours: "",
    services: "272 vouchers available in Washington County Rental assistance + VA case management For homeless veterans and families",
    notes: "",
    transportation: "",
  },
  {
    category: "Veteran Services",
    name: "Easterseals Oregon - Homeless Veteran Reintegration Program",
    address: "",
    phone: "",
    hours: "",
    services: "Employment assistance for veterans Housing support",
    notes: "",
    transportation: "",
  },
  {
    category: "Veteran Services",
    name: "Community Action - Supportive Services for Veteran Families (SSVF)",
    address: "",
    phone: "503-640-3263",
    hours: "",
    services: "Phone: 503-640-3263 Housing stability, eviction prevention, benefits assistance",
    notes: "Email: communityconnect@caowash.org",
    transportation: "",
  },
  {
    category: "Veteran Services",
    name: "Oregon Veterans' Emergency Financial Assistance Program (OVEFAP)",
    address: "",
    phone: "",
    hours: "",
    services: "One-time emergency assistance For veterans and immediate family Housing, utilities, medical/dental, transportation expenses",
    notes: "",
    transportation: "",
  },
  {
    category: "Domestic Violence/Sexual Assault",
    name: "UNICA",
    address: "",
    phone: "",
    hours: "",
    services: "24/7 crisis support For Latina/o/e community experiencing domestic/sexual violence",
    notes: "",
    transportation: "",
  },
  {
    category: "Domestic Violence/Sexual Assault",
    name: "Oregon Coalition Against Domestic & Sexual Violence (OCADSV)",
    address: "",
    phone: "",
    hours: "",
    services: "Search tool for shelter, advocacy, legal services Includes tribe-specific entities",
    notes: "",
    transportation: "",
  },
  {
    category: "Youth & Family Services",
    name: "HomePlate Youth Services",
    address: "",
    phone: "503-320-8965",
    hours: "",
    services: "Drop-in services and street outreach Age 24 and younger",
    notes: "",
    transportation: "",
  },
  {
    category: "Youth & Family Services",
    name: "Safe Place for Youth",
    address: "",
    phone: "503-542-2717",
    hours: "",
    services: "Ages 12-20 Emergency shelter, basic needs, case management",
    notes: "",
    transportation: "",
  },
  {
    category: "Youth & Family Services",
    name: "Family Promise Services",
    address: "",
    phone: "",
    hours: "",
    services: "Family shelter and support Transitional housing programs",
    notes: "",
    transportation: "",
  },
  {
    category: "Specialized Services",
    name: "Centro Cultural de Washington County",
    address: "",
    phone: "",
    hours: "",
    services: "Comprehensive services for Latino families Workforce training, youth programs, elder services, food pantry Casa Amparo transitional housing Cornelius Place (affordable housing for seniors)",
    notes: "Website: centrocultural.org.",
    transportation: "",
  },
  {
    category: "Specialized Services",
    name: "NARA (Northwest Portland Area Indian Health Board)",
    address: "",
    phone: "",
    hours: "",
    services: "Culturally-specific healthcare and services Substance use treatment",
    notes: "",
    transportation: "",
  },
  {
    category: "Specialized Services",
    name: "Native American Youth and Family Center (NAYA)",
    address: "",
    phone: "",
    hours: "",
    services: "Portland metro area Education, community involvement, culturally-specific programming",
    notes: "",
    transportation: "",
  },
  {
    category: "Specialized Services",
    name: "Oregon Department of Veterans' Affairs LGBTQIA+ Services",
    address: "",
    phone: "",
    hours: "",
    services: "Specific services and resources available Contact Washington County Veteran Services for info",
    notes: "",
    transportation: "",
  },
  {
    category: "Government Benefits",
    name: "Oregon Department of Human Services (DHS) Offices",
    address: "5300 NE Elam Young Pkwy, Hillsboro, OR 97124",
    phone: "503-646-9952",
    hours: "",
    services: "Beaverton Office: 15625 SW Greystone Ct., Beaverton, OR 97006 Phone: 503-646-9952 Hillsboro Office: Phone: 503-693-4555 Tigard Office: Phone: 503-670-9711 Services Available: SNAP (Food Stamps) TANF (Temporary Assistance for Needy Families) Oregon Health Plan (Medicaid) Child care assistance (ERDC) Cash assistance",
    notes: "",
    transportation: "",
  },
  {
    category: "Transportation",
    name: "TriMet Reduced Fare Programs",
    address: "",
    phone: "",
    hours: "",
    services: "Partner organizations help obtain reduced fares Just Compassion is partner organization",
    notes: "",
    transportation: "",
  },
  {
    category: "Transportation",
    name: "Tri-Met Trip Planner",
    address: "",
    phone: "",
    hours: "",
    services: "Use to plan routes to services, medical appointments",
    notes: "Website: trimet.org.",
    transportation: "",
  },
  {
    category: "Furniture & Household",
    name: "Community Warehouse",
    address: "",
    phone: "",
    hours: "",
    services: "Essential furnishings for neighbors in need Locations in Portland and Tigard Community partnerships",
    notes: "",
    transportation: "",
  },
  {
    category: "Legal Services",
    name: "211 Info",
    address: "",
    phone: "503-222-5555",
    hours: "",
    services: "Can provide referrals for ID and document assistance",
    notes: "",
    transportation: "",
  },
  {
    category: "Community Resources",
    name: "Housing Authority of Washington County",
    address: "",
    phone: "",
    hours: "",
    services: "Rental assistance voucher programs Regional Long-term Rent Assistance (RLRA) vouchers Section 8 Housing Choice Vouchers",
    notes: "",
    transportation: "",
  },
  {
    category: "Community Resources",
    name: "Free mobile hotspots and devices",
    address: "",
    phone: "",
    hours: "",
    services: "For K-12 students eligible for National School Lunch Program Contact schools or Community Action for info",
    notes: "",
    transportation: "",
  },
  {
    category: "Community Resources",
    name: "Street Roots",
    address: "",
    phone: "",
    hours: "",
    services: "Weekly social justice newspaper Sold by people experiencing homelessness to earn income",
    notes: "",
    transportation: "",
  },
];
